#define processing_system_unps_logic_spc_tile_sp_type sp2600_control
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_stat_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spc_tile_sp_sl_stat_ip
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port(m)         sp2600_control_sl_stat_ip_cell_port
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_control_sl_stat_ip_, m), _address)
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spc_tile_sp_sl_dmem_ip
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port(m)         sp2600_control_sl_dmem_ip_cell_port
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_control_sl_dmem_ip_, m), _address)
#define processing_system_unps_logic_spc_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spc_tile_spsp2600_control_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_unps_logic_spc_tile_spsp2600_control_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_unps_logic_spc_tile_spsp2600_control_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_unps_logic_spc_tile_sp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_unps_logic_spp_tile0_sp_type sp2600_proxy
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_stat_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spp_tile0_sp_sl_stat_ip
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port(m)         sp2600_proxy_sl_stat_ip_cell_port
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_proxy_sl_stat_ip_, m), _address)
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spp_tile0_sp_sl_dmem_ip
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port(m)         sp2600_proxy_sl_dmem_ip_cell_port
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_proxy_sl_dmem_ip_, m), _address)
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_unps_logic_spp_tile0_spsp2600_proxy_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_unps_logic_spp_tile0_sp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_unps_logic_spp_tile1_sp_type sp2600_proxy
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_stat_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spp_tile1_sp_sl_stat_ip
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port(m)         sp2600_proxy_sl_stat_ip_cell_port
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_proxy_sl_stat_ip_, m), _address)
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spp_tile1_sp_sl_dmem_ip
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port(m)         sp2600_proxy_sl_dmem_ip_cell_port
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_proxy_sl_dmem_ip_, m), _address)
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_unps_logic_spp_tile1_spsp2600_proxy_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_unps_logic_spp_tile1_sp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_unps_logic_spf_tile_sp_type sp2600_fp
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_stat_ip_cell_port_bus_slave_port                 processing_system_unps_logic_spf_tile_sp_sl_stat_ip
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_stat_ip_cell_port_connected_cell_port(m)         sp2600_fp_sl_stat_ip_cell_port
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_fp_sl_stat_ip_, m), _address)
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip0_cell_port_bus_slave_port                 processing_system_unps_logic_spf_tile_sp_sl_dmem_ip0
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip0_cell_port_connected_cell_port(m)         sp2600_fp_sl_dmem_ip0_cell_port
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip0_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_fp_sl_dmem_ip0_, m), _address)
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip0_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip1_cell_port_bus_slave_port                 processing_system_unps_logic_spf_tile_sp_sl_dmem_ip1
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip1_cell_port_connected_cell_port(m)         sp2600_fp_sl_dmem_ip1_cell_port
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip1_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_fp_sl_dmem_ip1_, m), _address)
#define processing_system_unps_logic_spf_tile_spsp2600_fp_sl_dmem_ip1_cell_port_connected_cell_port_message(m) NULL
#define processing_system_unps_logic_spf_tile_spsp2600_fp_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_unps_logic_spf_tile_spsp2600_fp_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_unps_logic_spf_tile_spsp2600_fp_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_unps_logic_spf_tile_sp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_isp_tile0_logic_isp_type isp2600
#define processing_system_isp_tile0_logic_ispisp2600_sl_stat_ip_cell_port_bus_slave_port                 processing_system_isp_tile0_logic_isp_sl_stat_ip
#define processing_system_isp_tile0_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port(m)         isp2600_sl_stat_ip_cell_port
#define processing_system_isp_tile0_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_stat_ip_, m), _address)
#define processing_system_isp_tile0_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile0_logic_ispisp2600_sl_pmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile0_logic_isp_sl_pmem_ip
#define processing_system_isp_tile0_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_pmem_ip_cell_port
#define processing_system_isp_tile0_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_pmem_ip_, m), _address)
#define processing_system_isp_tile0_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile0_logic_ispisp2600_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile0_logic_isp_sl_dmem_ip
#define processing_system_isp_tile0_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_dmem_ip_cell_port
#define processing_system_isp_tile0_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_dmem_ip_, m), _address)
#define processing_system_isp_tile0_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile0_logic_ispisp2600_sl_bmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile0_logic_isp_sl_bmem_ip
#define processing_system_isp_tile0_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_bmem_ip_cell_port
#define processing_system_isp_tile0_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_bmem_ip_, m), _address)
#define processing_system_isp_tile0_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile0_logic_ispisp2600_sl_vmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile0_logic_isp_sl_vmem_ip
#define processing_system_isp_tile0_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_vmem_ip_cell_port
#define processing_system_isp_tile0_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_vmem_ip_, m), _address)
#define processing_system_isp_tile0_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile0_logic_ispisp2600_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_isp_tile0_logic_ispisp2600_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_isp_tile0_logic_ispisp2600_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_isp_tile0_logic_isp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_isp_tile1_logic_isp_type isp2600
#define processing_system_isp_tile1_logic_ispisp2600_sl_stat_ip_cell_port_bus_slave_port                 processing_system_isp_tile1_logic_isp_sl_stat_ip
#define processing_system_isp_tile1_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port(m)         isp2600_sl_stat_ip_cell_port
#define processing_system_isp_tile1_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_stat_ip_, m), _address)
#define processing_system_isp_tile1_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile1_logic_ispisp2600_sl_pmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile1_logic_isp_sl_pmem_ip
#define processing_system_isp_tile1_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_pmem_ip_cell_port
#define processing_system_isp_tile1_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_pmem_ip_, m), _address)
#define processing_system_isp_tile1_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile1_logic_ispisp2600_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile1_logic_isp_sl_dmem_ip
#define processing_system_isp_tile1_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_dmem_ip_cell_port
#define processing_system_isp_tile1_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_dmem_ip_, m), _address)
#define processing_system_isp_tile1_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile1_logic_ispisp2600_sl_bmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile1_logic_isp_sl_bmem_ip
#define processing_system_isp_tile1_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_bmem_ip_cell_port
#define processing_system_isp_tile1_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_bmem_ip_, m), _address)
#define processing_system_isp_tile1_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile1_logic_ispisp2600_sl_vmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile1_logic_isp_sl_vmem_ip
#define processing_system_isp_tile1_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_vmem_ip_cell_port
#define processing_system_isp_tile1_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_vmem_ip_, m), _address)
#define processing_system_isp_tile1_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile1_logic_ispisp2600_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_isp_tile1_logic_ispisp2600_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_isp_tile1_logic_ispisp2600_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_isp_tile1_logic_isp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_isp_tile2_logic_isp_type isp2600
#define processing_system_isp_tile2_logic_ispisp2600_sl_stat_ip_cell_port_bus_slave_port                 processing_system_isp_tile2_logic_isp_sl_stat_ip
#define processing_system_isp_tile2_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port(m)         isp2600_sl_stat_ip_cell_port
#define processing_system_isp_tile2_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_stat_ip_, m), _address)
#define processing_system_isp_tile2_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile2_logic_ispisp2600_sl_pmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile2_logic_isp_sl_pmem_ip
#define processing_system_isp_tile2_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_pmem_ip_cell_port
#define processing_system_isp_tile2_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_pmem_ip_, m), _address)
#define processing_system_isp_tile2_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile2_logic_ispisp2600_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile2_logic_isp_sl_dmem_ip
#define processing_system_isp_tile2_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_dmem_ip_cell_port
#define processing_system_isp_tile2_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_dmem_ip_, m), _address)
#define processing_system_isp_tile2_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile2_logic_ispisp2600_sl_bmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile2_logic_isp_sl_bmem_ip
#define processing_system_isp_tile2_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_bmem_ip_cell_port
#define processing_system_isp_tile2_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_bmem_ip_, m), _address)
#define processing_system_isp_tile2_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile2_logic_ispisp2600_sl_vmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile2_logic_isp_sl_vmem_ip
#define processing_system_isp_tile2_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_vmem_ip_cell_port
#define processing_system_isp_tile2_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_vmem_ip_, m), _address)
#define processing_system_isp_tile2_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile2_logic_ispisp2600_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_isp_tile2_logic_ispisp2600_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_isp_tile2_logic_ispisp2600_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_isp_tile2_logic_isp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define processing_system_isp_tile3_logic_isp_type isp2600
#define processing_system_isp_tile3_logic_ispisp2600_sl_stat_ip_cell_port_bus_slave_port                 processing_system_isp_tile3_logic_isp_sl_stat_ip
#define processing_system_isp_tile3_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port(m)         isp2600_sl_stat_ip_cell_port
#define processing_system_isp_tile3_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_stat_ip_, m), _address)
#define processing_system_isp_tile3_logic_ispisp2600_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile3_logic_ispisp2600_sl_pmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile3_logic_isp_sl_pmem_ip
#define processing_system_isp_tile3_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_pmem_ip_cell_port
#define processing_system_isp_tile3_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_pmem_ip_, m), _address)
#define processing_system_isp_tile3_logic_ispisp2600_sl_pmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile3_logic_ispisp2600_sl_dmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile3_logic_isp_sl_dmem_ip
#define processing_system_isp_tile3_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_dmem_ip_cell_port
#define processing_system_isp_tile3_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_dmem_ip_, m), _address)
#define processing_system_isp_tile3_logic_ispisp2600_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile3_logic_ispisp2600_sl_bmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile3_logic_isp_sl_bmem_ip
#define processing_system_isp_tile3_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_bmem_ip_cell_port
#define processing_system_isp_tile3_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_bmem_ip_, m), _address)
#define processing_system_isp_tile3_logic_ispisp2600_sl_bmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile3_logic_ispisp2600_sl_vmem_ip_cell_port_bus_slave_port                 processing_system_isp_tile3_logic_isp_sl_vmem_ip
#define processing_system_isp_tile3_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port(m)         isp2600_sl_vmem_ip_cell_port
#define processing_system_isp_tile3_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2600_sl_vmem_ip_, m), _address)
#define processing_system_isp_tile3_logic_ispisp2600_sl_vmem_ip_cell_port_connected_cell_port_message(m) NULL
#define processing_system_isp_tile3_logic_ispisp2600_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define processing_system_isp_tile3_logic_ispisp2600_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define processing_system_isp_tile3_logic_ispisp2600_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define processing_system_isp_tile3_logic_isp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port



#define processing_system_unps_logic_spc_tile_sp_sl_stat_ip_error_message NULL
#define processing_system_unps_logic_spc_tile_sp_sl_stat_ip_master_port_address 0x0
#define processing_system_unps_logic_spc_tile_sp_sl_dmem_ip_error_message NULL
#define processing_system_unps_logic_spc_tile_sp_sl_dmem_ip_master_port_address 0x8000
#define processing_system_unps_logic_spc_tile_sp_imt_op_data_width 0x20
#define processing_system_unps_logic_spc_tile_sp_qmt_op_data_width 0x20
#define processing_system_unps_logic_spc_tile_sp_cmt_op_data_width 0x20
#define processing_system_unps_logic_spc_tile_sp_xmt_op_data_width 0x20

#define processing_system_unps_logic_spp_tile0_sp_sl_stat_ip_error_message NULL
#define processing_system_unps_logic_spp_tile0_sp_sl_stat_ip_master_port_address 0x20000
#define processing_system_unps_logic_spp_tile0_sp_sl_dmem_ip_error_message NULL
#define processing_system_unps_logic_spp_tile0_sp_sl_dmem_ip_master_port_address 0x28000
#define processing_system_unps_logic_spp_tile0_sp_imt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile0_sp_qmt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile0_sp_cmt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile0_sp_xmt_op_data_width 0x20

#define processing_system_unps_logic_spp_tile1_sp_sl_stat_ip_error_message NULL
#define processing_system_unps_logic_spp_tile1_sp_sl_stat_ip_master_port_address 0x30000
#define processing_system_unps_logic_spp_tile1_sp_sl_dmem_ip_error_message NULL
#define processing_system_unps_logic_spp_tile1_sp_sl_dmem_ip_master_port_address 0x38000
#define processing_system_unps_logic_spp_tile1_sp_imt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile1_sp_qmt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile1_sp_cmt_op_data_width 0x20
#define processing_system_unps_logic_spp_tile1_sp_xmt_op_data_width 0x20

#define processing_system_unps_logic_spf_tile_sp_sl_stat_ip_error_message NULL
#define processing_system_unps_logic_spf_tile_sp_sl_stat_ip_master_port_address 0x40000
#define processing_system_unps_logic_spf_tile_sp_sl_dmem_ip0_error_message NULL
#define processing_system_unps_logic_spf_tile_sp_sl_dmem_ip0_master_port_address 0x48000
#define processing_system_unps_logic_spf_tile_sp_sl_dmem_ip1_error_message NULL
#define processing_system_unps_logic_spf_tile_sp_sl_dmem_ip1_master_port_address 0x58000
#define processing_system_unps_logic_spf_tile_sp_imt_op_data_width 0x40
#define processing_system_unps_logic_spf_tile_sp_qmt_op_data_width 0x20
#define processing_system_unps_logic_spf_tile_sp_cmt_op_data_width 0x20
#define processing_system_unps_logic_spf_tile_sp_xmt_op_data_width 0x20

#define processing_system_isp_tile0_logic_isp_sl_stat_ip_error_message NULL
#define processing_system_isp_tile0_logic_isp_sl_stat_ip_master_port_address 0x1C0000
#define processing_system_isp_tile0_logic_isp_sl_pmem_ip_error_message NULL
#define processing_system_isp_tile0_logic_isp_sl_pmem_ip_master_port_address 0x1D0000
#define processing_system_isp_tile0_logic_isp_sl_dmem_ip_error_message NULL
#define processing_system_isp_tile0_logic_isp_sl_dmem_ip_master_port_address 0x1F0000
#define processing_system_isp_tile0_logic_isp_sl_bmem_ip_error_message NULL
#define processing_system_isp_tile0_logic_isp_sl_bmem_ip_master_port_address 0x200000
#define processing_system_isp_tile0_logic_isp_sl_vmem_ip_error_message NULL
#define processing_system_isp_tile0_logic_isp_sl_vmem_ip_master_port_address 0x220000
#define processing_system_isp_tile0_logic_isp_imt_op_data_width 0x200
#define processing_system_isp_tile0_logic_isp_qmt_op_data_width 0x20
#define processing_system_isp_tile0_logic_isp_cmt_op_data_width 0x20
#define processing_system_isp_tile0_logic_isp_xmt_op_data_width 0x20
#define processing_system_isp_tile0_logic_isp_mt_bmem_op_data_width 0x200

#define processing_system_isp_tile1_logic_isp_sl_stat_ip_error_message NULL
#define processing_system_isp_tile1_logic_isp_sl_stat_ip_master_port_address 0x240000
#define processing_system_isp_tile1_logic_isp_sl_pmem_ip_error_message NULL
#define processing_system_isp_tile1_logic_isp_sl_pmem_ip_master_port_address 0x250000
#define processing_system_isp_tile1_logic_isp_sl_dmem_ip_error_message NULL
#define processing_system_isp_tile1_logic_isp_sl_dmem_ip_master_port_address 0x270000
#define processing_system_isp_tile1_logic_isp_sl_bmem_ip_error_message NULL
#define processing_system_isp_tile1_logic_isp_sl_bmem_ip_master_port_address 0x280000
#define processing_system_isp_tile1_logic_isp_sl_vmem_ip_error_message NULL
#define processing_system_isp_tile1_logic_isp_sl_vmem_ip_master_port_address 0x2A0000
#define processing_system_isp_tile1_logic_isp_imt_op_data_width 0x200
#define processing_system_isp_tile1_logic_isp_qmt_op_data_width 0x20
#define processing_system_isp_tile1_logic_isp_cmt_op_data_width 0x20
#define processing_system_isp_tile1_logic_isp_xmt_op_data_width 0x20
#define processing_system_isp_tile1_logic_isp_mt_bmem_op_data_width 0x200

#define processing_system_isp_tile2_logic_isp_sl_stat_ip_error_message NULL
#define processing_system_isp_tile2_logic_isp_sl_stat_ip_master_port_address 0x2C0000
#define processing_system_isp_tile2_logic_isp_sl_pmem_ip_error_message NULL
#define processing_system_isp_tile2_logic_isp_sl_pmem_ip_master_port_address 0x2D0000
#define processing_system_isp_tile2_logic_isp_sl_dmem_ip_error_message NULL
#define processing_system_isp_tile2_logic_isp_sl_dmem_ip_master_port_address 0x2F0000
#define processing_system_isp_tile2_logic_isp_sl_bmem_ip_error_message NULL
#define processing_system_isp_tile2_logic_isp_sl_bmem_ip_master_port_address 0x300000
#define processing_system_isp_tile2_logic_isp_sl_vmem_ip_error_message NULL
#define processing_system_isp_tile2_logic_isp_sl_vmem_ip_master_port_address 0x320000
#define processing_system_isp_tile2_logic_isp_imt_op_data_width 0x200
#define processing_system_isp_tile2_logic_isp_qmt_op_data_width 0x20
#define processing_system_isp_tile2_logic_isp_cmt_op_data_width 0x20
#define processing_system_isp_tile2_logic_isp_xmt_op_data_width 0x20
#define processing_system_isp_tile2_logic_isp_mt_bmem_op_data_width 0x200

#define processing_system_isp_tile3_logic_isp_sl_stat_ip_error_message NULL
#define processing_system_isp_tile3_logic_isp_sl_stat_ip_master_port_address 0x340000
#define processing_system_isp_tile3_logic_isp_sl_pmem_ip_error_message NULL
#define processing_system_isp_tile3_logic_isp_sl_pmem_ip_master_port_address 0x350000
#define processing_system_isp_tile3_logic_isp_sl_dmem_ip_error_message NULL
#define processing_system_isp_tile3_logic_isp_sl_dmem_ip_master_port_address 0x370000
#define processing_system_isp_tile3_logic_isp_sl_bmem_ip_error_message NULL
#define processing_system_isp_tile3_logic_isp_sl_bmem_ip_master_port_address 0x380000
#define processing_system_isp_tile3_logic_isp_sl_vmem_ip_error_message NULL
#define processing_system_isp_tile3_logic_isp_sl_vmem_ip_master_port_address 0x3A0000
#define processing_system_isp_tile3_logic_isp_imt_op_data_width 0x200
#define processing_system_isp_tile3_logic_isp_qmt_op_data_width 0x20
#define processing_system_isp_tile3_logic_isp_cmt_op_data_width 0x20
#define processing_system_isp_tile3_logic_isp_xmt_op_data_width 0x20
#define processing_system_isp_tile3_logic_isp_mt_bmem_op_data_width 0x200

