#ifndef _VIED_NCI_EQ_STORAGE_CLASS_H
#define _VIED_NCI_EQ_STORAGE_CLASS_H


#include "storage_class.h"

#ifndef __INLINE_VIED_NCI_EQ__
#define VIED_NCI_EQ_STORAGE_CLASS_H STORAGE_CLASS_EXTERN
#define VIED_NCI_EQ_STORAGE_CLASS_C
#else				/* __INLINE_VIED_NCI_EQ__ */
#define VIED_NCI_EQ_STORAGE_CLASS_H STORAGE_CLASS_INLINE
#define VIED_NCI_EQ_STORAGE_CLASS_C STORAGE_CLASS_INLINE
#endif				/* __INLINE_VIED_NCI_EQ__ */

#endif /* _VIED_NCI_EQ_STORAGE_CLASS_H */
