obj-$(CONFIG_VIDEO_CSS2600)	+= drivers/media/pci/css2600/
ifndef CONFIG_VIDEO_CSS2600_2401
obj-$(CONFIG_VIDEO_CSS2600_PSYS)	+= drivers/media/pci/css2600/lib2600psys/
endif
obj-$(CONFIG_VIDEO_CSS2600_DEBUG)	+= drivers/media/pci/css2600/debug_if/
obj-$(CONFIG_CSS2600_STUB)	+= drivers/media/platform/css2600/


