// generated file from <device>_reg_descr.hsd by hive_crgen.pl
#ifndef _ga_acb_ccbcr_h
#define _ga_acb_ccbcr_h


#define  GA_ACB_BASE_CTRL_ADDR  0x00004
#define  GA_ACB_CMD_FIFO_TAIL_ADDR  0x00000
#define  GA_ACB_DFD_ACTION_ATTRIBUTES_ADDR  0x00034
#define  GA_ACB_DFD_ACTION_CTRL_ADDR  0x0002c
#define  GA_ACB_DFD_DISABLE_ADDR  0x0001c
#define  GA_ACB_DFD_EXPLICIT_FW_TRIG_ADDR  0x00024
#define  GA_ACB_DFD_LOCATION_2_CAPTURE_ADDR  0x00030
#define  GA_ACB_DFD_RESUME_NORMAL_OP_ADDR  0x00020
#define  GA_ACB_GA_ACB_DFD_TRACED_DATA_COORDINATES_ADDR  0x0003c
#define  GA_ACB_DFD_TRIGGER_CAUGHT_ADDR  0x00038
#define  GA_ACB_DFD_TRIGGER_MODE_ADDR  0x00028
#define  GA_ACB_GA_ACB_HW_ASSR_CLEAR_ADDR  0x00040
#define  GA_ACB_GA_ACB_HW_ASSR_MASK_ADDR  0x00044
#define  GA_ACB_GA_ACB_HW_ASSR_RAW_STAT_ADDR  0x0004c
#define  GA_ACB_GA_ACB_HW_ASSR_STAT_ADDR  0x00048
#define  GA_ACB_INPUT_FRAME_SIZE_ADDR  0x00008
#define  GA_ACB_SCALE_ADDR  0x0000c
#define  GA_ACB_SOFT_RESET_ADDR  0x00018
#define  GA_ACB_STTS_CURR_ACTV_CMD_ADDR  0x00010
#define  GA_ACB_STTS_FRAME_LOCATION_ADDR  0x00014






#define GA_ACB_CCBCR_PARAM \
CONSTANT  GA_ACB_CMD_FIFO_TAIL_REG_ID    : INTEGER := 0 ; \
CONSTANT  GA_ACB_BASE_CTRL_REG_ID    : INTEGER := 1 ; \
CONSTANT  GA_ACB_INPUT_FRAME_SIZE_REG_ID    : INTEGER := 2 ; \
CONSTANT  GA_ACB_SCALE_REG_ID    : INTEGER := 3 ; \
CONSTANT  GA_ACB_STTS_CURR_ACTV_CMD_REG_ID    : INTEGER := 4 ; \
CONSTANT  GA_ACB_STTS_FRAME_LOCATION_REG_ID    : INTEGER := 5 ; \
CONSTANT  GA_ACB_SOFT_RESET_REG_ID    : INTEGER := 6 ; \
CONSTANT  GA_ACB_DFD_DISABLE_REG_ID    : INTEGER := 7 ; \
CONSTANT  GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID    : INTEGER := 8 ; \
CONSTANT  GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID    : INTEGER := 9 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_MODE_REG_ID    : INTEGER := 10 ; \
CONSTANT  GA_ACB_DFD_ACTION_CTRL_REG_ID    : INTEGER := 11 ; \
CONSTANT  GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID    : INTEGER := 12 ; \
CONSTANT  GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID    : INTEGER := 13 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID    : INTEGER := 14 ; \
CONSTANT  GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID    : INTEGER := 15 ; \
CONSTANT  GA_ACB_HW_ASSR_CLEAR_REG_ID    : INTEGER := 16 ; \
CONSTANT  GA_ACB_HW_ASSR_MASK_REG_ID    : INTEGER := 17 ; \
CONSTANT  GA_ACB_HW_ASSR_STAT_REG_ID    : INTEGER := 18 ; \
CONSTANT  GA_ACB_HW_ASSR_RAW_STAT_REG_ID    : INTEGER := 19 ; \
\
CONSTANT  GA_ACB_BASE_CTRL_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_CMD_FIFO_TAIL_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_ACTION_ATTRIBUTES_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_ACTION_CTRL_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_DISABLE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_LOCATION_2_CAPTURE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_RESUME_NORMAL_OP_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_CAUGHT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_MODE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_HW_ASSR_CLEAR_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_HW_ASSR_MASK_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_HW_ASSR_RAW_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_HW_ASSR_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_INPUT_FRAME_SIZE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_SCALE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_SOFT_RESET_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_STTS_CURR_ACTV_CMD_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  GA_ACB_STTS_FRAME_LOCATION_REG_WIDTH    : INTEGER := 32 ; \
\
CONSTANT  GA_ACB_BASE_CTRL_REG_RSTVAL    : NATURAL := 256 ; \
CONSTANT  GA_ACB_CMD_FIFO_TAIL_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_DFD_ACTION_ATTRIBUTES_REG_RSTVAL    : NATURAL := 1 ; \
CONSTANT  GA_ACB_DFD_ACTION_CTRL_REG_RSTVAL    : NATURAL := 2032 ; \
CONSTANT  GA_ACB_DFD_DISABLE_REG_RSTVAL    : NATURAL := 1 ; \
CONSTANT  GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_DFD_LOCATION_2_CAPTURE_REG_RSTVAL    : NATURAL := 65535 ; \
CONSTANT  GA_ACB_DFD_RESUME_NORMAL_OP_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_CAUGHT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_DFD_TRIGGER_MODE_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_HW_ASSR_CLEAR_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_HW_ASSR_MASK_REG_RSTVAL    : NATURAL := 15 ; \
CONSTANT  GA_ACB_HW_ASSR_RAW_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_HW_ASSR_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_INPUT_FRAME_SIZE_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_SCALE_REG_RSTVAL    : NATURAL := 1 ; \
CONSTANT  GA_ACB_SOFT_RESET_REG_RSTVAL    : NATURAL := 16 ; \
CONSTANT  GA_ACB_STTS_CURR_ACTV_CMD_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  GA_ACB_STTS_FRAME_LOCATION_REG_RSTVAL    : NATURAL := 0 ; \
\
CONSTANT  GA_ACB_NOF_REGS : NATURAL := 20 ; \
CONSTANT  GA_ACB_NOF_REGS_BANK : NATURAL := 20 ; \
CONSTANT  c_num_of_regs : NATURAL := 20 ; \
CONSTANT  c_num_of_regs_bank : NATURAL :=  20; \
\
\
CONSTANT p_data_width                             : D1<INTEGER>; \
p_data_width{GA_ACB_BASE_CTRL_REG_ID} := GA_ACB_BASE_CTRL_REG_WIDTH   ; \
p_data_width{GA_ACB_CMD_FIFO_TAIL_REG_ID} := GA_ACB_CMD_FIFO_TAIL_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID} := GA_ACB_DFD_ACTION_ATTRIBUTES_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_ACTION_CTRL_REG_ID} := GA_ACB_DFD_ACTION_CTRL_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_DISABLE_REG_ID} := GA_ACB_DFD_DISABLE_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID} := GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID} := GA_ACB_DFD_LOCATION_2_CAPTURE_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID} := GA_ACB_DFD_RESUME_NORMAL_OP_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID} := GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID} := GA_ACB_DFD_TRIGGER_CAUGHT_REG_WIDTH   ; \
p_data_width{GA_ACB_DFD_TRIGGER_MODE_REG_ID} := GA_ACB_DFD_TRIGGER_MODE_REG_WIDTH   ; \
p_data_width{GA_ACB_HW_ASSR_CLEAR_REG_ID} := GA_ACB_HW_ASSR_CLEAR_REG_WIDTH   ; \
p_data_width{GA_ACB_HW_ASSR_MASK_REG_ID} := GA_ACB_HW_ASSR_MASK_REG_WIDTH   ; \
p_data_width{GA_ACB_HW_ASSR_RAW_STAT_REG_ID} := GA_ACB_HW_ASSR_RAW_STAT_REG_WIDTH   ; \
p_data_width{GA_ACB_HW_ASSR_STAT_REG_ID} := GA_ACB_HW_ASSR_STAT_REG_WIDTH   ; \
p_data_width{GA_ACB_INPUT_FRAME_SIZE_REG_ID} := GA_ACB_INPUT_FRAME_SIZE_REG_WIDTH   ; \
p_data_width{GA_ACB_SCALE_REG_ID} := GA_ACB_SCALE_REG_WIDTH   ; \
p_data_width{GA_ACB_SOFT_RESET_REG_ID} := GA_ACB_SOFT_RESET_REG_WIDTH   ; \
p_data_width{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID} := GA_ACB_STTS_CURR_ACTV_CMD_REG_WIDTH   ; \
p_data_width{GA_ACB_STTS_FRAME_LOCATION_REG_ID} := GA_ACB_STTS_FRAME_LOCATION_REG_WIDTH   ; \
\
FEATURE c_reg_rst_val                             : D1<BITVECTOR>; \
c_reg_rst_val{GA_ACB_BASE_CTRL_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_BASE_CTRL_REG_RSTVAL), p_data_width{GA_ACB_BASE_CTRL_REG_ID})); \
c_reg_rst_val{GA_ACB_CMD_FIFO_TAIL_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_CMD_FIFO_TAIL_REG_RSTVAL), p_data_width{GA_ACB_CMD_FIFO_TAIL_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_ACTION_ATTRIBUTES_REG_RSTVAL), p_data_width{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_ACTION_CTRL_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_ACTION_CTRL_REG_RSTVAL), p_data_width{GA_ACB_DFD_ACTION_CTRL_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_DISABLE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_DISABLE_REG_RSTVAL), p_data_width{GA_ACB_DFD_DISABLE_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_RSTVAL), p_data_width{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_LOCATION_2_CAPTURE_REG_RSTVAL), p_data_width{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_RESUME_NORMAL_OP_REG_RSTVAL), p_data_width{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_RSTVAL), p_data_width{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_TRIGGER_CAUGHT_REG_RSTVAL), p_data_width{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID})); \
c_reg_rst_val{GA_ACB_DFD_TRIGGER_MODE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_DFD_TRIGGER_MODE_REG_RSTVAL), p_data_width{GA_ACB_DFD_TRIGGER_MODE_REG_ID})); \
c_reg_rst_val{GA_ACB_HW_ASSR_CLEAR_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_HW_ASSR_CLEAR_REG_RSTVAL), p_data_width{GA_ACB_HW_ASSR_CLEAR_REG_ID})); \
c_reg_rst_val{GA_ACB_HW_ASSR_MASK_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_HW_ASSR_MASK_REG_RSTVAL), p_data_width{GA_ACB_HW_ASSR_MASK_REG_ID})); \
c_reg_rst_val{GA_ACB_HW_ASSR_RAW_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_HW_ASSR_RAW_STAT_REG_RSTVAL), p_data_width{GA_ACB_HW_ASSR_RAW_STAT_REG_ID})); \
c_reg_rst_val{GA_ACB_HW_ASSR_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_HW_ASSR_STAT_REG_RSTVAL), p_data_width{GA_ACB_HW_ASSR_STAT_REG_ID})); \
c_reg_rst_val{GA_ACB_INPUT_FRAME_SIZE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_INPUT_FRAME_SIZE_REG_RSTVAL), p_data_width{GA_ACB_INPUT_FRAME_SIZE_REG_ID})); \
c_reg_rst_val{GA_ACB_SCALE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_SCALE_REG_RSTVAL), p_data_width{GA_ACB_SCALE_REG_ID})); \
c_reg_rst_val{GA_ACB_SOFT_RESET_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_SOFT_RESET_REG_RSTVAL), p_data_width{GA_ACB_SOFT_RESET_REG_ID})); \
c_reg_rst_val{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_STTS_CURR_ACTV_CMD_REG_RSTVAL), p_data_width{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID})); \
c_reg_rst_val{GA_ACB_STTS_FRAME_LOCATION_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(GA_ACB_STTS_FRAME_LOCATION_REG_RSTVAL), p_data_width{GA_ACB_STTS_FRAME_LOCATION_REG_ID})); \
\
FEATURE p_reg_wmask                             : D1<BITVECTOR>;  \
 p_reg_wmask{GA_ACB_BASE_CTRL_REG_ID}  := X"0001FF0F";\
 p_reg_wmask{GA_ACB_CMD_FIFO_TAIL_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID}  := X"00000011";\
 p_reg_wmask{GA_ACB_DFD_ACTION_CTRL_REG_ID}  := X"000007F3";\
 p_reg_wmask{GA_ACB_DFD_DISABLE_REG_ID}  := X"00000001";\
 p_reg_wmask{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID}  := X"00000001";\
 p_reg_wmask{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID}  := X"00000001";\
 p_reg_wmask{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID}  := X"00000000";\
 p_reg_wmask{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID}  := X"00000000";\
 p_reg_wmask{GA_ACB_DFD_TRIGGER_MODE_REG_ID}  := X"00000013";\
 p_reg_wmask{GA_ACB_HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_wmask{GA_ACB_HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_wmask{GA_ACB_HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{GA_ACB_HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{GA_ACB_INPUT_FRAME_SIZE_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{GA_ACB_SCALE_REG_ID}  := X"000000FF";\
 p_reg_wmask{GA_ACB_SOFT_RESET_REG_ID}  := X"000000FF";\
 p_reg_wmask{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID}  := X"00000000";\
 p_reg_wmask{GA_ACB_STTS_FRAME_LOCATION_REG_ID}  := X"00000000";\
\
FEATURE p_reg_rmask                             : D1<BITVECTOR>;  \
 p_reg_rmask{GA_ACB_BASE_CTRL_REG_ID}  := X"0001FF0F";\
 p_reg_rmask{GA_ACB_CMD_FIFO_TAIL_REG_ID}  := X"00000000";\
 p_reg_rmask{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID}  := X"00000011";\
 p_reg_rmask{GA_ACB_DFD_ACTION_CTRL_REG_ID}  := X"000007F3";\
 p_reg_rmask{GA_ACB_DFD_DISABLE_REG_ID}  := X"00000001";\
 p_reg_rmask{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID}  := X"00000001";\
 p_reg_rmask{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID}  := X"00000001";\
 p_reg_rmask{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID}  := X"00000001";\
 p_reg_rmask{GA_ACB_DFD_TRIGGER_MODE_REG_ID}  := X"00000013";\
 p_reg_rmask{GA_ACB_HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_rmask{GA_ACB_HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_rmask{GA_ACB_HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{GA_ACB_HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{GA_ACB_INPUT_FRAME_SIZE_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{GA_ACB_SCALE_REG_ID}  := X"000000FF";\
 p_reg_rmask{GA_ACB_SOFT_RESET_REG_ID}  := X"000000FF";\
 p_reg_rmask{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{GA_ACB_STTS_FRAME_LOCATION_REG_ID}  := X"FFFFFFFF";\
\
FEATURE p_reg_womask                             : D1<BITVECTOR>;  \
 p_reg_womask{GA_ACB_BASE_CTRL_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_CMD_FIFO_TAIL_REG_ID}  := X"FFFFFFFF";\
 p_reg_womask{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_ACTION_CTRL_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_DISABLE_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_DFD_TRIGGER_MODE_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_INPUT_FRAME_SIZE_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_SCALE_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_SOFT_RESET_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID}  := X"00000000";\
 p_reg_womask{GA_ACB_STTS_FRAME_LOCATION_REG_ID}  := X"00000000";\
\
FEATURE p_reg_romask                             : D1<BITVECTOR>;  \
 p_reg_romask{GA_ACB_BASE_CTRL_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_CMD_FIFO_TAIL_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_ACTION_CTRL_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_DISABLE_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID}  := X"FFFFFFFF";\
 p_reg_romask{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID}  := X"00000001";\
 p_reg_romask{GA_ACB_DFD_TRIGGER_MODE_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{GA_ACB_HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{GA_ACB_INPUT_FRAME_SIZE_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_SCALE_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_SOFT_RESET_REG_ID}  := X"00000000";\
 p_reg_romask{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID}  := X"FFFFFFFF";\
 p_reg_romask{GA_ACB_STTS_FRAME_LOCATION_REG_ID}  := X"FFFFFFFF";\
\
FEATURE p_func_en                             : D1<BOOLEAN>;  \
 p_func_en{GA_ACB_BASE_CTRL_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_CMD_FIFO_TAIL_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_ACTION_ATTRIBUTES_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_ACTION_CTRL_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_DISABLE_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_EXPLICIT_FW_TRIG_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_LOCATION_2_CAPTURE_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_RESUME_NORMAL_OP_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_DFD_TRACED_DATA_COORDINATES_REG_ID}  := TRUE; \
 p_func_en{GA_ACB_DFD_TRIGGER_CAUGHT_REG_ID}  := TRUE; \
 p_func_en{GA_ACB_DFD_TRIGGER_MODE_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_HW_ASSR_CLEAR_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_HW_ASSR_MASK_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_HW_ASSR_RAW_STAT_REG_ID}  := TRUE; \
 p_func_en{GA_ACB_HW_ASSR_STAT_REG_ID}  := TRUE; \
 p_func_en{GA_ACB_INPUT_FRAME_SIZE_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_SCALE_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_SOFT_RESET_REG_ID}  := FALSE; \
 p_func_en{GA_ACB_STTS_CURR_ACTV_CMD_REG_ID}  := TRUE; \
 p_func_en{GA_ACB_STTS_FRAME_LOCATION_REG_ID}  := TRUE; \


#define GA_ACB_CCBCR_SIGNALS \
SIGNAL func_en                                : D1<BIT>(GA_ACB_NOF_REGS_BANK); \
SIGNAL wire_reg_we                            : D1<BIT>(GA_ACB_NOF_REGS_BANK); \
SIGNAL wire_reg_outputs                       : D1<BITVECTOR>(p_data_width); \
SIGNAL func_data                              : D1<BITVECTOR>(p_data_width);

#define GA_ACB_BASE_CTRL_FORK_ACB_OUTPUT_RANGE   16 
#define GA_ACB_BASE_CTRL_IGNORE_LINENUM_RANGE   2 
#define GA_ACB_BASE_CTRL_PIXPAIR_REP_NUM_RANGE   15 DOWNTO 8 
#define GA_ACB_BASE_CTRL_PIX_REP_EN_RANGE   3 
#define GA_ACB_BASE_CTRL_ACC_IN_SELECT_RANGE   0 
#define GA_ACB_BASE_CTRL_ACC_OUT_SELECT_RANGE   1 
#define GA_ACB_DFD_ACTION_ATTRIBUTES_NUM_OF_COULMNS_PER_IT_RANGE   4 
#define GA_ACB_DFD_ACTION_ATTRIBUTES_NUM_OF_LINES_PER_IT_RANGE   0 
#define GA_ACB_DFD_ACTION_CTRL_DFD_ACTION_RANGE   1 DOWNTO 0 
#define GA_ACB_DFD_ACTION_CTRL_DFD_ACTION_DELAY_RANGE   10 DOWNTO 4 
#define GA_ACB_DFD_DISABLE_DFD_DISABLE_RANGE   0 
#define GA_ACB_DFD_EXPLICIT_FW_TRIG_EXPLICIT_FW_TRIG_RANGE   0 
#define GA_ACB_DFD_LOCATION_2_CAPTURE_HOR_LOCATION_2_CAPTURE_RANGE   15 DOWNTO 0 
#define GA_ACB_DFD_LOCATION_2_CAPTURE_VER_LOCATION_2_CAPTURE_RANGE   31 DOWNTO 16 
#define GA_ACB_DFD_RESUME_NORMAL_OP_DFD_RESUME_NOR_OP_RANGE   0 
#define GA_ACB_DFD_TRACED_DATA_COORDINATES_DFD_TRACED_HOR_LOC_RANGE   15 DOWNTO 0 
#define GA_ACB_DFD_TRACED_DATA_COORDINATES_DFD_TRACED_VERTICAL_LOC_RANGE   31 DOWNTO 16 
#define GA_ACB_DFD_TRIGGER_CAUGHT_DFD_TRIGGER_CAUGHT_RANGE   0 
#define GA_ACB_DFD_TRIGGER_MODE_TRIG_ACB_RANGE   4 
#define GA_ACB_DFD_TRIGGER_MODE_TRIG_CORR_TO_RANGE   1 DOWNTO 0 
#define GA_ACB_HW_ASSR_CLEAR_CLEAR_RANGE   3 DOWNTO 0 
#define GA_ACB_HW_ASSR_MASK_MASK_RANGE   3 DOWNTO 0 
#define GA_ACB_HW_ASSR_RAW_STAT_STAT_RANGE   3 DOWNTO 0 
#define GA_ACB_HW_ASSR_STAT_STAT_RANGE   3 DOWNTO 0 
#define GA_ACB_INPUT_FRAME_SIZE_HSIZE_RANGE   15 DOWNTO 0 
#define GA_ACB_INPUT_FRAME_SIZE_VSIZE_RANGE   31 DOWNTO 16 
#define GA_ACB_SCALE_SCALE_MULT_RANGE   3 DOWNTO 0 
#define GA_ACB_SCALE_SCALE_NF_RANGE   7 DOWNTO 4 
#define GA_ACB_SOFT_RESET_MAX_COUNT_RANGE   7 DOWNTO 0 
#define GA_ACB_STTS_FRAME_LOCATION_HOR_IDX_RANGE   15 DOWNTO 0 
#define GA_ACB_STTS_FRAME_LOCATION_VER_IDX_RANGE   31 DOWNTO 16 

#define GA_ACB_BASE_CTRL_ACC_IN_SELECT_WIDTH  1
#define GA_ACB_BASE_CTRL_ACC_OUT_SELECT_WIDTH  1
#define GA_ACB_BASE_CTRL_FORK_ACB_OUTPUT_WIDTH  1
#define GA_ACB_BASE_CTRL_IGNORE_LINENUM_WIDTH  1
#define GA_ACB_BASE_CTRL_PIXPAIR_REP_NUM_WIDTH  8
#define GA_ACB_BASE_CTRL_PIX_REP_EN_WIDTH  1
#define GA_ACB_DFD_ACTION_ATTRIBUTES_NUM_OF_COULMNS_PER_IT_WIDTH  1
#define GA_ACB_DFD_ACTION_ATTRIBUTES_NUM_OF_LINES_PER_IT_WIDTH  1
#define GA_ACB_DFD_ACTION_CTRL_DFD_ACTION_DELAY_WIDTH  7
#define GA_ACB_DFD_ACTION_CTRL_DFD_ACTION_WIDTH  2
#define GA_ACB_DFD_DISABLE_DFD_DISABLE_WIDTH  1
#define GA_ACB_DFD_EXPLICIT_FW_TRIG_EXPLICIT_FW_TRIG_WIDTH  1
#define GA_ACB_DFD_LOCATION_2_CAPTURE_HOR_LOCATION_2_CAPTURE_WIDTH  16
#define GA_ACB_DFD_LOCATION_2_CAPTURE_VER_LOCATION_2_CAPTURE_WIDTH  16
#define GA_ACB_DFD_RESUME_NORMAL_OP_DFD_RESUME_NOR_OP_WIDTH  1
#define GA_ACB_DFD_TRACED_DATA_COORDINATES_DFD_TRACED_HOR_LOC_WIDTH  16
#define GA_ACB_DFD_TRACED_DATA_COORDINATES_DFD_TRACED_VERTICAL_LOC_WIDTH  16
#define GA_ACB_DFD_TRIGGER_CAUGHT_DFD_TRIGGER_CAUGHT_WIDTH  1
#define GA_ACB_DFD_TRIGGER_MODE_TRIG_ACB_WIDTH  1
#define GA_ACB_DFD_TRIGGER_MODE_TRIG_CORR_TO_WIDTH  2
#define GA_ACB_HW_ASSR_CLEAR_CLEAR_WIDTH  4
#define GA_ACB_HW_ASSR_MASK_MASK_WIDTH  4
#define GA_ACB_HW_ASSR_RAW_STAT_STAT_WIDTH  4
#define GA_ACB_HW_ASSR_STAT_STAT_WIDTH  4
#define GA_ACB_INPUT_FRAME_SIZE_HSIZE_WIDTH  16
#define GA_ACB_INPUT_FRAME_SIZE_VSIZE_WIDTH  16
#define GA_ACB_SCALE_SCALE_MULT_WIDTH  4
#define GA_ACB_SCALE_SCALE_NF_WIDTH  4
#define GA_ACB_SOFT_RESET_MAX_COUNT_WIDTH  8
#define GA_ACB_STTS_FRAME_LOCATION_HOR_IDX_WIDTH  16
#define GA_ACB_STTS_FRAME_LOCATION_VER_IDX_WIDTH  16


#endif
