obj-$(CONFIG_GPIO_INTEL_MSIC)	+= intel_msic_gpio.o
obj-$(CONFIG_INTEL_MID_OSNIB_ILB)	+= intel_mid_osnib_ilb.o
obj-$(CONFIG_INTEL_MID_OSIP)	+= intel_mid_osip.o
obj-$(CONFIG_INTEL_PSH_IPC)	+= intel_psh_ipc.o
obj-$(CONFIG_INTEL_REBOOT_TARGET)	+= reboot_target.o
obj-$(CONFIG_INTEL_REBOOT_TARGET_UEFI) += reboot_target_uefi.o
