// generated file from <device>_reg_descr.hsd by hive_crgen.pl
#ifndef _ff_iefd_ccbcr_h
#define _ff_iefd_ccbcr_h


#define  CFGUNIT_CU1_ADDR  0x00000
#define  CFGUNIT_CU3_ADDR  0x0001c
#define  CFGUNIT_CU5_0_ADDR  0x00020
#define  CFGUNIT_CU5_1_ADDR  0x00024
#define  CFGUNIT_CU6_0_ADDR  0x00028
#define  CFGUNIT_CU6_1_ADDR  0x0002c
#define  CFGUNIT_CU6_2_ADDR  0x00030
#define  CFGUNIT_CU6_3_ADDR  0x00034
#define  CFGUNIT_CU7_ADDR  0x00038
#define  CFGUNIT_CUE_0_ADDR  0x00004
#define  CFGUNIT_CUE_1_ADDR  0x00008
#define  CFGUNIT_CUE_2_ADDR  0x0000c
#define  CFGUNIT_CUE_3_ADDR  0x00010
#define  CFGUNIT_CUE_4_ADDR  0x00014
#define  CFGUNIT_CUE_5_ADDR  0x00018
#define  CFGUNIT_CUR_0_ADDR  0x0004c
#define  CFGUNIT_CUR_1_ADDR  0x00050
#define  CFGUNIT_CUR_2_ADDR  0x00054
#define  CFGUNIT_CUR_3_ADDR  0x00058
#define  CFGUNIT_CUR_4_ADDR  0x0005c
#define  CFGUNIT_CUR_5_ADDR  0x00060
#define  CFGUNIT_CUR_6_ADDR  0x00064
#define  CFGUNIT_CUS_0_ADDR  0x0003c
#define  CFGUNIT_CUS_1_ADDR  0x00040
#define  CFGUNIT_CUS_2_ADDR  0x00044
#define  CFGUNIT_CUS_3_ADDR  0x00048
#define  CFGUNIT_CUV_ADDR  0x00068
#define  CUCFG0_ADDR  0x000a8
#define  CUCFG1_ADDR  0x000ac
#define  FF_IEFD_DFD_DATA_READ_CMD_ADDR  0x000d0
#define  FF_IEFD_DFD_DATA_READ_COMPLETION_ADDR  0x000cc
#define  FF_IEFD_DFD_EN_ADDR  0x000bc
#define  FF_IEFD_DFD_SINGLE_STEP_ADDR  0x000c0
#define  FF_IEFD_DFD_TRACED_DATA_ADDR  0x000c4
#define  FF_IEFD_DFD_TRACED_DATA_VALID_ADDR  0x000c8
#define  FF_IEFD_HW_ASSR_CLEAR_ADDR  0x000d4
#define  FF_IEFD_HW_ASSR_MASK_ADDR  0x000d8
#define  FF_IEFD_HW_ASSR_RAW_STAT_ADDR  0x000e0
#define  FF_IEFD_HW_ASSR_STAT_ADDR  0x000dc
#define  IEFD_CONFIG_ADDR  0x0006c
#define  IEFD_CONTROL_ADDR  0x00070
#define  M_FAR_W_ADDR  0x00084
#define  M_RAD_FAR_W_ADDR  0x000a4
#define  M_SHRPN_NEGA_LMT_DIR_ADDR  0x0007c
#define  M_SHRPN_NEGA_LMT_TXT_ADDR  0x00074
#define  M_SHRPN_POSI_LMT_DIR_ADDR  0x00080
#define  M_SHRPN_POSI_LMT_TXT_ADDR  0x00078
#define  FF_IEFD_PWR_FEATURE_ADDR  0x000b8
#define  RADIALCFG_ADDR  0x000a0
#define  RADIALRESETX2_ADDR  0x00098
#define  RADIALRESETXY_ADDR  0x00094
#define  RADIALRESETY2_ADDR  0x0009c
#define  UNSHARPCFG_ADDR  0x00088
#define  UNSHARPCOEF0_ADDR  0x0008c
#define  UNSHARPCOEF1_ADDR  0x00090
#define  VSS_LUT_X_ADDR  0x000b0
#define  VSS_LUT_Y_ADDR  0x000b4






#define FF_IEFD_CCBCR_PARAM \
CONSTANT  CFGUNIT_CU1_REG_ID    : INTEGER := 0 ; \
CONSTANT  CFGUNIT_CUE_0_REG_ID    : INTEGER := 1 ; \
CONSTANT  CFGUNIT_CUE_1_REG_ID    : INTEGER := 2 ; \
CONSTANT  CFGUNIT_CUE_2_REG_ID    : INTEGER := 3 ; \
CONSTANT  CFGUNIT_CUE_3_REG_ID    : INTEGER := 4 ; \
CONSTANT  CFGUNIT_CUE_4_REG_ID    : INTEGER := 5 ; \
CONSTANT  CFGUNIT_CUE_5_REG_ID    : INTEGER := 6 ; \
CONSTANT  CFGUNIT_CU3_REG_ID    : INTEGER := 7 ; \
CONSTANT  CFGUNIT_CU5_0_REG_ID    : INTEGER := 8 ; \
CONSTANT  CFGUNIT_CU5_1_REG_ID    : INTEGER := 9 ; \
CONSTANT  CFGUNIT_CU6_0_REG_ID    : INTEGER := 10 ; \
CONSTANT  CFGUNIT_CU6_1_REG_ID    : INTEGER := 11 ; \
CONSTANT  CFGUNIT_CU6_2_REG_ID    : INTEGER := 12 ; \
CONSTANT  CFGUNIT_CU6_3_REG_ID    : INTEGER := 13 ; \
CONSTANT  CFGUNIT_CU7_REG_ID    : INTEGER := 14 ; \
CONSTANT  CFGUNIT_CUS_0_REG_ID    : INTEGER := 15 ; \
CONSTANT  CFGUNIT_CUS_1_REG_ID    : INTEGER := 16 ; \
CONSTANT  CFGUNIT_CUS_2_REG_ID    : INTEGER := 17 ; \
CONSTANT  CFGUNIT_CUS_3_REG_ID    : INTEGER := 18 ; \
CONSTANT  CFGUNIT_CUR_0_REG_ID    : INTEGER := 19 ; \
CONSTANT  CFGUNIT_CUR_1_REG_ID    : INTEGER := 20 ; \
CONSTANT  CFGUNIT_CUR_2_REG_ID    : INTEGER := 21 ; \
CONSTANT  CFGUNIT_CUR_3_REG_ID    : INTEGER := 22 ; \
CONSTANT  CFGUNIT_CUR_4_REG_ID    : INTEGER := 23 ; \
CONSTANT  CFGUNIT_CUR_5_REG_ID    : INTEGER := 24 ; \
CONSTANT  CFGUNIT_CUR_6_REG_ID    : INTEGER := 25 ; \
CONSTANT  CFGUNIT_CUV_REG_ID    : INTEGER := 26 ; \
CONSTANT  IEFD_CONFIG_REG_ID    : INTEGER := 27 ; \
CONSTANT  IEFD_CONTROL_REG_ID    : INTEGER := 28 ; \
CONSTANT  M_SHRPN_NEGA_LMT_TXT_REG_ID    : INTEGER := 29 ; \
CONSTANT  M_SHRPN_POSI_LMT_TXT_REG_ID    : INTEGER := 30 ; \
CONSTANT  M_SHRPN_NEGA_LMT_DIR_REG_ID    : INTEGER := 31 ; \
CONSTANT  M_SHRPN_POSI_LMT_DIR_REG_ID    : INTEGER := 32 ; \
CONSTANT  M_FAR_W_REG_ID    : INTEGER := 33 ; \
CONSTANT  UNSHARPCFG_REG_ID    : INTEGER := 34 ; \
CONSTANT  UNSHARPCOEF0_REG_ID    : INTEGER := 35 ; \
CONSTANT  UNSHARPCOEF1_REG_ID    : INTEGER := 36 ; \
CONSTANT  RADIALRESETXY_REG_ID    : INTEGER := 37 ; \
CONSTANT  RADIALRESETX2_REG_ID    : INTEGER := 38 ; \
CONSTANT  RADIALRESETY2_REG_ID    : INTEGER := 39 ; \
CONSTANT  RADIALCFG_REG_ID    : INTEGER := 40 ; \
CONSTANT  M_RAD_FAR_W_REG_ID    : INTEGER := 41 ; \
CONSTANT  CUCFG0_REG_ID    : INTEGER := 42 ; \
CONSTANT  CUCFG1_REG_ID    : INTEGER := 43 ; \
CONSTANT  VSS_LUT_X_REG_ID    : INTEGER := 44 ; \
CONSTANT  VSS_LUT_Y_REG_ID    : INTEGER := 45 ; \
CONSTANT  PWR_FEATURE_REG_ID    : INTEGER := 46 ; \
CONSTANT  DFD_EN_REG_ID    : INTEGER := 47 ; \
CONSTANT  DFD_SINGLE_STEP_REG_ID    : INTEGER := 48 ; \
CONSTANT  DFD_TRACED_DATA_REG_ID    : INTEGER := 49 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_ID    : INTEGER := 50 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_ID    : INTEGER := 51 ; \
CONSTANT  DFD_DATA_READ_CMD_REG_ID    : INTEGER := 52 ; \
CONSTANT  HW_ASSR_CLEAR_REG_ID    : INTEGER := 53 ; \
CONSTANT  HW_ASSR_MASK_REG_ID    : INTEGER := 54 ; \
CONSTANT  HW_ASSR_STAT_REG_ID    : INTEGER := 55 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_ID    : INTEGER := 56 ; \
\
CONSTANT  CFGUNIT_CU1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU5_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU5_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU6_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU6_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU6_2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU6_3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CU7_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_4_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUE_5_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_4_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_5_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUR_6_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUS_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUS_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUS_2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUS_3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CFGUNIT_CUV_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CUCFG0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  CUCFG1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_DATA_READ_CMD_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_EN_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_SINGLE_STEP_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_TRACED_DATA_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_CLEAR_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_MASK_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  IEFD_CONFIG_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  IEFD_CONTROL_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_FAR_W_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_RAD_FAR_W_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_SHRPN_NEGA_LMT_DIR_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_SHRPN_NEGA_LMT_TXT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_SHRPN_POSI_LMT_DIR_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  M_SHRPN_POSI_LMT_TXT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  PWR_FEATURE_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  RADIALCFG_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  RADIALRESETX2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  RADIALRESETXY_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  RADIALRESETY2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  UNSHARPCFG_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  UNSHARPCOEF0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  UNSHARPCOEF1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  VSS_LUT_X_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  VSS_LUT_Y_REG_WIDTH    : INTEGER := 32 ; \
\
CONSTANT  CFGUNIT_CU1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU5_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU5_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU6_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU6_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU6_2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU6_3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CU7_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_4_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUE_5_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_4_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_5_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUR_6_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUS_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUS_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUS_2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUS_3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CFGUNIT_CUV_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CUCFG0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  CUCFG1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_DATA_READ_CMD_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_EN_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_SINGLE_STEP_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_TRACED_DATA_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_CLEAR_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_MASK_REG_RSTVAL    : NATURAL := 15 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  IEFD_CONFIG_REG_RSTVAL    : NATURAL := 134217736 ; \
CONSTANT  IEFD_CONTROL_REG_RSTVAL    : NATURAL := 31 ; \
CONSTANT  M_FAR_W_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  M_RAD_FAR_W_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  M_SHRPN_NEGA_LMT_DIR_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  M_SHRPN_NEGA_LMT_TXT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  M_SHRPN_POSI_LMT_DIR_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  M_SHRPN_POSI_LMT_TXT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  PWR_FEATURE_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  RADIALCFG_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  RADIALRESETX2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  RADIALRESETXY_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  RADIALRESETY2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  UNSHARPCFG_REG_RSTVAL    : NATURAL := 16 ; \
CONSTANT  UNSHARPCOEF0_REG_RSTVAL    : NATURAL := 2361857 ; \
CONSTANT  UNSHARPCOEF1_REG_RSTVAL    : NATURAL := 25194013 ; \
CONSTANT  VSS_LUT_X_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  VSS_LUT_Y_REG_RSTVAL    : NATURAL := 0 ; \
\
CONSTANT  FF_IEFD_NOF_REGS : NATURAL := 57 ; \
CONSTANT  FF_IEFD_NOF_REGS_BANK : NATURAL := 57 ; \
CONSTANT  c_num_of_regs : NATURAL := 57 ; \
CONSTANT  c_num_of_regs_bank : NATURAL :=  57; \
\
\
CONSTANT p_data_width                             : D1<INTEGER>; \
p_data_width{CFGUNIT_CU1_REG_ID} := CFGUNIT_CU1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU3_REG_ID} := CFGUNIT_CU3_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU5_0_REG_ID} := CFGUNIT_CU5_0_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU5_1_REG_ID} := CFGUNIT_CU5_1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU6_0_REG_ID} := CFGUNIT_CU6_0_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU6_1_REG_ID} := CFGUNIT_CU6_1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU6_2_REG_ID} := CFGUNIT_CU6_2_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU6_3_REG_ID} := CFGUNIT_CU6_3_REG_WIDTH   ; \
p_data_width{CFGUNIT_CU7_REG_ID} := CFGUNIT_CU7_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_0_REG_ID} := CFGUNIT_CUE_0_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_1_REG_ID} := CFGUNIT_CUE_1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_2_REG_ID} := CFGUNIT_CUE_2_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_3_REG_ID} := CFGUNIT_CUE_3_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_4_REG_ID} := CFGUNIT_CUE_4_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUE_5_REG_ID} := CFGUNIT_CUE_5_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_0_REG_ID} := CFGUNIT_CUR_0_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_1_REG_ID} := CFGUNIT_CUR_1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_2_REG_ID} := CFGUNIT_CUR_2_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_3_REG_ID} := CFGUNIT_CUR_3_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_4_REG_ID} := CFGUNIT_CUR_4_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_5_REG_ID} := CFGUNIT_CUR_5_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUR_6_REG_ID} := CFGUNIT_CUR_6_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUS_0_REG_ID} := CFGUNIT_CUS_0_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUS_1_REG_ID} := CFGUNIT_CUS_1_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUS_2_REG_ID} := CFGUNIT_CUS_2_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUS_3_REG_ID} := CFGUNIT_CUS_3_REG_WIDTH   ; \
p_data_width{CFGUNIT_CUV_REG_ID} := CFGUNIT_CUV_REG_WIDTH   ; \
p_data_width{CUCFG0_REG_ID} := CUCFG0_REG_WIDTH   ; \
p_data_width{CUCFG1_REG_ID} := CUCFG1_REG_WIDTH   ; \
p_data_width{DFD_DATA_READ_CMD_REG_ID} := DFD_DATA_READ_CMD_REG_WIDTH   ; \
p_data_width{DFD_DATA_READ_COMPLETION_REG_ID} := DFD_DATA_READ_COMPLETION_REG_WIDTH   ; \
p_data_width{DFD_EN_REG_ID} := DFD_EN_REG_WIDTH   ; \
p_data_width{DFD_SINGLE_STEP_REG_ID} := DFD_SINGLE_STEP_REG_WIDTH   ; \
p_data_width{DFD_TRACED_DATA_REG_ID} := DFD_TRACED_DATA_REG_WIDTH   ; \
p_data_width{DFD_TRACED_DATA_VALID_REG_ID} := DFD_TRACED_DATA_VALID_REG_WIDTH   ; \
p_data_width{HW_ASSR_CLEAR_REG_ID} := HW_ASSR_CLEAR_REG_WIDTH   ; \
p_data_width{HW_ASSR_MASK_REG_ID} := HW_ASSR_MASK_REG_WIDTH   ; \
p_data_width{HW_ASSR_RAW_STAT_REG_ID} := HW_ASSR_RAW_STAT_REG_WIDTH   ; \
p_data_width{HW_ASSR_STAT_REG_ID} := HW_ASSR_STAT_REG_WIDTH   ; \
p_data_width{IEFD_CONFIG_REG_ID} := IEFD_CONFIG_REG_WIDTH   ; \
p_data_width{IEFD_CONTROL_REG_ID} := IEFD_CONTROL_REG_WIDTH   ; \
p_data_width{M_FAR_W_REG_ID} := M_FAR_W_REG_WIDTH   ; \
p_data_width{M_RAD_FAR_W_REG_ID} := M_RAD_FAR_W_REG_WIDTH   ; \
p_data_width{M_SHRPN_NEGA_LMT_DIR_REG_ID} := M_SHRPN_NEGA_LMT_DIR_REG_WIDTH   ; \
p_data_width{M_SHRPN_NEGA_LMT_TXT_REG_ID} := M_SHRPN_NEGA_LMT_TXT_REG_WIDTH   ; \
p_data_width{M_SHRPN_POSI_LMT_DIR_REG_ID} := M_SHRPN_POSI_LMT_DIR_REG_WIDTH   ; \
p_data_width{M_SHRPN_POSI_LMT_TXT_REG_ID} := M_SHRPN_POSI_LMT_TXT_REG_WIDTH   ; \
p_data_width{PWR_FEATURE_REG_ID} := PWR_FEATURE_REG_WIDTH   ; \
p_data_width{RADIALCFG_REG_ID} := RADIALCFG_REG_WIDTH   ; \
p_data_width{RADIALRESETX2_REG_ID} := RADIALRESETX2_REG_WIDTH   ; \
p_data_width{RADIALRESETXY_REG_ID} := RADIALRESETXY_REG_WIDTH   ; \
p_data_width{RADIALRESETY2_REG_ID} := RADIALRESETY2_REG_WIDTH   ; \
p_data_width{UNSHARPCFG_REG_ID} := UNSHARPCFG_REG_WIDTH   ; \
p_data_width{UNSHARPCOEF0_REG_ID} := UNSHARPCOEF0_REG_WIDTH   ; \
p_data_width{UNSHARPCOEF1_REG_ID} := UNSHARPCOEF1_REG_WIDTH   ; \
p_data_width{VSS_LUT_X_REG_ID} := VSS_LUT_X_REG_WIDTH   ; \
p_data_width{VSS_LUT_Y_REG_ID} := VSS_LUT_Y_REG_WIDTH   ; \
\
FEATURE c_reg_rst_val                             : D1<BITVECTOR>; \
c_reg_rst_val{CFGUNIT_CU1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU1_REG_RSTVAL), p_data_width{CFGUNIT_CU1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU3_REG_RSTVAL), p_data_width{CFGUNIT_CU3_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU5_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU5_0_REG_RSTVAL), p_data_width{CFGUNIT_CU5_0_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU5_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU5_1_REG_RSTVAL), p_data_width{CFGUNIT_CU5_1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU6_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU6_0_REG_RSTVAL), p_data_width{CFGUNIT_CU6_0_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU6_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU6_1_REG_RSTVAL), p_data_width{CFGUNIT_CU6_1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU6_2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU6_2_REG_RSTVAL), p_data_width{CFGUNIT_CU6_2_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU6_3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU6_3_REG_RSTVAL), p_data_width{CFGUNIT_CU6_3_REG_ID})); \
c_reg_rst_val{CFGUNIT_CU7_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CU7_REG_RSTVAL), p_data_width{CFGUNIT_CU7_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_0_REG_RSTVAL), p_data_width{CFGUNIT_CUE_0_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_1_REG_RSTVAL), p_data_width{CFGUNIT_CUE_1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_2_REG_RSTVAL), p_data_width{CFGUNIT_CUE_2_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_3_REG_RSTVAL), p_data_width{CFGUNIT_CUE_3_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_4_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_4_REG_RSTVAL), p_data_width{CFGUNIT_CUE_4_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUE_5_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUE_5_REG_RSTVAL), p_data_width{CFGUNIT_CUE_5_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_0_REG_RSTVAL), p_data_width{CFGUNIT_CUR_0_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_1_REG_RSTVAL), p_data_width{CFGUNIT_CUR_1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_2_REG_RSTVAL), p_data_width{CFGUNIT_CUR_2_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_3_REG_RSTVAL), p_data_width{CFGUNIT_CUR_3_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_4_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_4_REG_RSTVAL), p_data_width{CFGUNIT_CUR_4_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_5_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_5_REG_RSTVAL), p_data_width{CFGUNIT_CUR_5_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUR_6_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUR_6_REG_RSTVAL), p_data_width{CFGUNIT_CUR_6_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUS_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUS_0_REG_RSTVAL), p_data_width{CFGUNIT_CUS_0_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUS_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUS_1_REG_RSTVAL), p_data_width{CFGUNIT_CUS_1_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUS_2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUS_2_REG_RSTVAL), p_data_width{CFGUNIT_CUS_2_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUS_3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUS_3_REG_RSTVAL), p_data_width{CFGUNIT_CUS_3_REG_ID})); \
c_reg_rst_val{CFGUNIT_CUV_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CFGUNIT_CUV_REG_RSTVAL), p_data_width{CFGUNIT_CUV_REG_ID})); \
c_reg_rst_val{CUCFG0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CUCFG0_REG_RSTVAL), p_data_width{CUCFG0_REG_ID})); \
c_reg_rst_val{CUCFG1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(CUCFG1_REG_RSTVAL), p_data_width{CUCFG1_REG_ID})); \
c_reg_rst_val{DFD_DATA_READ_CMD_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_DATA_READ_CMD_REG_RSTVAL), p_data_width{DFD_DATA_READ_CMD_REG_ID})); \
c_reg_rst_val{DFD_DATA_READ_COMPLETION_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_DATA_READ_COMPLETION_REG_RSTVAL), p_data_width{DFD_DATA_READ_COMPLETION_REG_ID})); \
c_reg_rst_val{DFD_EN_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_EN_REG_RSTVAL), p_data_width{DFD_EN_REG_ID})); \
c_reg_rst_val{DFD_SINGLE_STEP_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_SINGLE_STEP_REG_RSTVAL), p_data_width{DFD_SINGLE_STEP_REG_ID})); \
c_reg_rst_val{DFD_TRACED_DATA_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_TRACED_DATA_REG_RSTVAL), p_data_width{DFD_TRACED_DATA_REG_ID})); \
c_reg_rst_val{DFD_TRACED_DATA_VALID_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_TRACED_DATA_VALID_REG_RSTVAL), p_data_width{DFD_TRACED_DATA_VALID_REG_ID})); \
c_reg_rst_val{HW_ASSR_CLEAR_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_CLEAR_REG_RSTVAL), p_data_width{HW_ASSR_CLEAR_REG_ID})); \
c_reg_rst_val{HW_ASSR_MASK_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_MASK_REG_RSTVAL), p_data_width{HW_ASSR_MASK_REG_ID})); \
c_reg_rst_val{HW_ASSR_RAW_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_RAW_STAT_REG_RSTVAL), p_data_width{HW_ASSR_RAW_STAT_REG_ID})); \
c_reg_rst_val{HW_ASSR_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_STAT_REG_RSTVAL), p_data_width{HW_ASSR_STAT_REG_ID})); \
c_reg_rst_val{IEFD_CONFIG_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(IEFD_CONFIG_REG_RSTVAL), p_data_width{IEFD_CONFIG_REG_ID})); \
c_reg_rst_val{IEFD_CONTROL_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(IEFD_CONTROL_REG_RSTVAL), p_data_width{IEFD_CONTROL_REG_ID})); \
c_reg_rst_val{M_FAR_W_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_FAR_W_REG_RSTVAL), p_data_width{M_FAR_W_REG_ID})); \
c_reg_rst_val{M_RAD_FAR_W_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_RAD_FAR_W_REG_RSTVAL), p_data_width{M_RAD_FAR_W_REG_ID})); \
c_reg_rst_val{M_SHRPN_NEGA_LMT_DIR_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_SHRPN_NEGA_LMT_DIR_REG_RSTVAL), p_data_width{M_SHRPN_NEGA_LMT_DIR_REG_ID})); \
c_reg_rst_val{M_SHRPN_NEGA_LMT_TXT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_SHRPN_NEGA_LMT_TXT_REG_RSTVAL), p_data_width{M_SHRPN_NEGA_LMT_TXT_REG_ID})); \
c_reg_rst_val{M_SHRPN_POSI_LMT_DIR_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_SHRPN_POSI_LMT_DIR_REG_RSTVAL), p_data_width{M_SHRPN_POSI_LMT_DIR_REG_ID})); \
c_reg_rst_val{M_SHRPN_POSI_LMT_TXT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(M_SHRPN_POSI_LMT_TXT_REG_RSTVAL), p_data_width{M_SHRPN_POSI_LMT_TXT_REG_ID})); \
c_reg_rst_val{PWR_FEATURE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(PWR_FEATURE_REG_RSTVAL), p_data_width{PWR_FEATURE_REG_ID})); \
c_reg_rst_val{RADIALCFG_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(RADIALCFG_REG_RSTVAL), p_data_width{RADIALCFG_REG_ID})); \
c_reg_rst_val{RADIALRESETX2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(RADIALRESETX2_REG_RSTVAL), p_data_width{RADIALRESETX2_REG_ID})); \
c_reg_rst_val{RADIALRESETXY_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(RADIALRESETXY_REG_RSTVAL), p_data_width{RADIALRESETXY_REG_ID})); \
c_reg_rst_val{RADIALRESETY2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(RADIALRESETY2_REG_RSTVAL), p_data_width{RADIALRESETY2_REG_ID})); \
c_reg_rst_val{UNSHARPCFG_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(UNSHARPCFG_REG_RSTVAL), p_data_width{UNSHARPCFG_REG_ID})); \
c_reg_rst_val{UNSHARPCOEF0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(UNSHARPCOEF0_REG_RSTVAL), p_data_width{UNSHARPCOEF0_REG_ID})); \
c_reg_rst_val{UNSHARPCOEF1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(UNSHARPCOEF1_REG_RSTVAL), p_data_width{UNSHARPCOEF1_REG_ID})); \
c_reg_rst_val{VSS_LUT_X_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(VSS_LUT_X_REG_RSTVAL), p_data_width{VSS_LUT_X_REG_ID})); \
c_reg_rst_val{VSS_LUT_Y_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(VSS_LUT_Y_REG_RSTVAL), p_data_width{VSS_LUT_Y_REG_ID})); \
\
FEATURE p_reg_wmask                             : D1<BITVECTOR>;  \
 p_reg_wmask{CFGUNIT_CU1_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CU3_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CU5_0_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CU5_1_REG_ID}  := X"000000FF";\
 p_reg_wmask{CFGUNIT_CU6_0_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CU6_1_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CU6_2_REG_ID}  := X"01FFFFFF";\
 p_reg_wmask{CFGUNIT_CU6_3_REG_ID}  := X"000000FF";\
 p_reg_wmask{CFGUNIT_CU7_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUE_0_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUE_1_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUE_2_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUE_3_REG_ID}  := X"0003FFFF";\
 p_reg_wmask{CFGUNIT_CUE_4_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUE_5_REG_ID}  := X"0003FFFF";\
 p_reg_wmask{CFGUNIT_CUR_0_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{CFGUNIT_CUR_1_REG_ID}  := X"0000FFFF";\
 p_reg_wmask{CFGUNIT_CUR_2_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{CFGUNIT_CUR_3_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{CFGUNIT_CUR_4_REG_ID}  := X"0000FFFF";\
 p_reg_wmask{CFGUNIT_CUR_5_REG_ID}  := X"3FFFFFFF";\
 p_reg_wmask{CFGUNIT_CUR_6_REG_ID}  := X"000FFFFF";\
 p_reg_wmask{CFGUNIT_CUS_0_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUS_1_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CFGUNIT_CUS_2_REG_ID}  := X"01FFFFFF";\
 p_reg_wmask{CFGUNIT_CUS_3_REG_ID}  := X"000000FF";\
 p_reg_wmask{CFGUNIT_CUV_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{CUCFG0_REG_ID}  := X"3F7F3F7F";\
 p_reg_wmask{CUCFG1_REG_ID}  := X"0007FDFF";\
 p_reg_wmask{DFD_DATA_READ_CMD_REG_ID}  := X"00000001";\
 p_reg_wmask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000000";\
 p_reg_wmask{DFD_EN_REG_ID}  := X"00000111";\
 p_reg_wmask{DFD_SINGLE_STEP_REG_ID}  := X"00000001";\
 p_reg_wmask{DFD_TRACED_DATA_REG_ID}  := X"00000000";\
 p_reg_wmask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000000";\
 p_reg_wmask{HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_wmask{HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_wmask{HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{IEFD_CONFIG_REG_ID}  := X"7F1F3F7F";\
 p_reg_wmask{IEFD_CONTROL_REG_ID}  := X"0000001F";\
 p_reg_wmask{M_FAR_W_REG_ID}  := X"007F7F7F";\
 p_reg_wmask{M_RAD_FAR_W_REG_ID}  := X"007F7F7F";\
 p_reg_wmask{M_SHRPN_NEGA_LMT_DIR_REG_ID}  := X"00001FFF";\
 p_reg_wmask{M_SHRPN_NEGA_LMT_TXT_REG_ID}  := X"00001FFF";\
 p_reg_wmask{M_SHRPN_POSI_LMT_DIR_REG_ID}  := X"00001FFF";\
 p_reg_wmask{M_SHRPN_POSI_LMT_TXT_REG_ID}  := X"00001FFF";\
 p_reg_wmask{PWR_FEATURE_REG_ID}  := X"00000003";\
 p_reg_wmask{RADIALCFG_REG_ID}  := X"00007F0F";\
 p_reg_wmask{RADIALRESETX2_REG_ID}  := X"00FFFFFF";\
 p_reg_wmask{RADIALRESETXY_REG_ID}  := X"1FFF1FFF";\
 p_reg_wmask{RADIALRESETY2_REG_ID}  := X"00FFFFFF";\
 p_reg_wmask{UNSHARPCFG_REG_ID}  := X"0001FF7F";\
 p_reg_wmask{UNSHARPCOEF0_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{UNSHARPCOEF1_REG_ID}  := X"07FFFFFF";\
 p_reg_wmask{VSS_LUT_X_REG_ID}  := X"00FFFFFF";\
 p_reg_wmask{VSS_LUT_Y_REG_ID}  := X"000F0F0F";\
\
FEATURE p_reg_rmask                             : D1<BITVECTOR>;  \
 p_reg_rmask{CFGUNIT_CU1_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CU3_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CU5_0_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CU5_1_REG_ID}  := X"000000FF";\
 p_reg_rmask{CFGUNIT_CU6_0_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CU6_1_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CU6_2_REG_ID}  := X"01FFFFFF";\
 p_reg_rmask{CFGUNIT_CU6_3_REG_ID}  := X"000000FF";\
 p_reg_rmask{CFGUNIT_CU7_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUE_0_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUE_1_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUE_2_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUE_3_REG_ID}  := X"0003FFFF";\
 p_reg_rmask{CFGUNIT_CUE_4_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUE_5_REG_ID}  := X"0003FFFF";\
 p_reg_rmask{CFGUNIT_CUR_0_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{CFGUNIT_CUR_1_REG_ID}  := X"0000FFFF";\
 p_reg_rmask{CFGUNIT_CUR_2_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{CFGUNIT_CUR_3_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{CFGUNIT_CUR_4_REG_ID}  := X"0000FFFF";\
 p_reg_rmask{CFGUNIT_CUR_5_REG_ID}  := X"3FFFFFFF";\
 p_reg_rmask{CFGUNIT_CUR_6_REG_ID}  := X"000FFFFF";\
 p_reg_rmask{CFGUNIT_CUS_0_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUS_1_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CFGUNIT_CUS_2_REG_ID}  := X"01FFFFFF";\
 p_reg_rmask{CFGUNIT_CUS_3_REG_ID}  := X"000000FF";\
 p_reg_rmask{CFGUNIT_CUV_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{CUCFG0_REG_ID}  := X"3F7F3F7F";\
 p_reg_rmask{CUCFG1_REG_ID}  := X"0007FDFF";\
 p_reg_rmask{DFD_DATA_READ_CMD_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_EN_REG_ID}  := X"00000111";\
 p_reg_rmask{DFD_SINGLE_STEP_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_TRACED_DATA_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000001";\
 p_reg_rmask{HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{IEFD_CONFIG_REG_ID}  := X"7F1F3F7F";\
 p_reg_rmask{IEFD_CONTROL_REG_ID}  := X"0000001F";\
 p_reg_rmask{M_FAR_W_REG_ID}  := X"007F7F7F";\
 p_reg_rmask{M_RAD_FAR_W_REG_ID}  := X"007F7F7F";\
 p_reg_rmask{M_SHRPN_NEGA_LMT_DIR_REG_ID}  := X"00001FFF";\
 p_reg_rmask{M_SHRPN_NEGA_LMT_TXT_REG_ID}  := X"00001FFF";\
 p_reg_rmask{M_SHRPN_POSI_LMT_DIR_REG_ID}  := X"00001FFF";\
 p_reg_rmask{M_SHRPN_POSI_LMT_TXT_REG_ID}  := X"00001FFF";\
 p_reg_rmask{PWR_FEATURE_REG_ID}  := X"00000003";\
 p_reg_rmask{RADIALCFG_REG_ID}  := X"00007F0F";\
 p_reg_rmask{RADIALRESETX2_REG_ID}  := X"00FFFFFF";\
 p_reg_rmask{RADIALRESETXY_REG_ID}  := X"1FFF1FFF";\
 p_reg_rmask{RADIALRESETY2_REG_ID}  := X"00FFFFFF";\
 p_reg_rmask{UNSHARPCFG_REG_ID}  := X"0001FF7F";\
 p_reg_rmask{UNSHARPCOEF0_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{UNSHARPCOEF1_REG_ID}  := X"07FFFFFF";\
 p_reg_rmask{VSS_LUT_X_REG_ID}  := X"00FFFFFF";\
 p_reg_rmask{VSS_LUT_Y_REG_ID}  := X"000F0F0F";\
\
FEATURE p_reg_womask                             : D1<BITVECTOR>;  \
 p_reg_womask{CFGUNIT_CU1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU3_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU5_0_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU5_1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU6_0_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU6_1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU6_2_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU6_3_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CU7_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_0_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_2_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_3_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_4_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUE_5_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_0_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_2_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_3_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_4_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_5_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUR_6_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUS_0_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUS_1_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUS_2_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUS_3_REG_ID}  := X"00000000";\
 p_reg_womask{CFGUNIT_CUV_REG_ID}  := X"00000000";\
 p_reg_womask{CUCFG0_REG_ID}  := X"00000000";\
 p_reg_womask{CUCFG1_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_DATA_READ_CMD_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_EN_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_SINGLE_STEP_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_TRACED_DATA_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{IEFD_CONFIG_REG_ID}  := X"00000000";\
 p_reg_womask{IEFD_CONTROL_REG_ID}  := X"00000000";\
 p_reg_womask{M_FAR_W_REG_ID}  := X"00000000";\
 p_reg_womask{M_RAD_FAR_W_REG_ID}  := X"00000000";\
 p_reg_womask{M_SHRPN_NEGA_LMT_DIR_REG_ID}  := X"00000000";\
 p_reg_womask{M_SHRPN_NEGA_LMT_TXT_REG_ID}  := X"00000000";\
 p_reg_womask{M_SHRPN_POSI_LMT_DIR_REG_ID}  := X"00000000";\
 p_reg_womask{M_SHRPN_POSI_LMT_TXT_REG_ID}  := X"00000000";\
 p_reg_womask{PWR_FEATURE_REG_ID}  := X"00000000";\
 p_reg_womask{RADIALCFG_REG_ID}  := X"00000000";\
 p_reg_womask{RADIALRESETX2_REG_ID}  := X"00000000";\
 p_reg_womask{RADIALRESETXY_REG_ID}  := X"00000000";\
 p_reg_womask{RADIALRESETY2_REG_ID}  := X"00000000";\
 p_reg_womask{UNSHARPCFG_REG_ID}  := X"00000000";\
 p_reg_womask{UNSHARPCOEF0_REG_ID}  := X"00000000";\
 p_reg_womask{UNSHARPCOEF1_REG_ID}  := X"00000000";\
 p_reg_womask{VSS_LUT_X_REG_ID}  := X"00000000";\
 p_reg_womask{VSS_LUT_Y_REG_ID}  := X"00000000";\
\
FEATURE p_reg_romask                             : D1<BITVECTOR>;  \
 p_reg_romask{CFGUNIT_CU1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU3_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU5_0_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU5_1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU6_0_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU6_1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU6_2_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU6_3_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CU7_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_0_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_2_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_3_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_4_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUE_5_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_0_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_2_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_3_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_4_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_5_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUR_6_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUS_0_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUS_1_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUS_2_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUS_3_REG_ID}  := X"00000000";\
 p_reg_romask{CFGUNIT_CUV_REG_ID}  := X"00000000";\
 p_reg_romask{CUCFG0_REG_ID}  := X"00000000";\
 p_reg_romask{CUCFG1_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_DATA_READ_CMD_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000001";\
 p_reg_romask{DFD_EN_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_SINGLE_STEP_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_TRACED_DATA_REG_ID}  := X"FFFFFFFF";\
 p_reg_romask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000001";\
 p_reg_romask{HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_romask{HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_romask{HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{IEFD_CONFIG_REG_ID}  := X"00000000";\
 p_reg_romask{IEFD_CONTROL_REG_ID}  := X"00000000";\
 p_reg_romask{M_FAR_W_REG_ID}  := X"00000000";\
 p_reg_romask{M_RAD_FAR_W_REG_ID}  := X"00000000";\
 p_reg_romask{M_SHRPN_NEGA_LMT_DIR_REG_ID}  := X"00000000";\
 p_reg_romask{M_SHRPN_NEGA_LMT_TXT_REG_ID}  := X"00000000";\
 p_reg_romask{M_SHRPN_POSI_LMT_DIR_REG_ID}  := X"00000000";\
 p_reg_romask{M_SHRPN_POSI_LMT_TXT_REG_ID}  := X"00000000";\
 p_reg_romask{PWR_FEATURE_REG_ID}  := X"00000000";\
 p_reg_romask{RADIALCFG_REG_ID}  := X"00000000";\
 p_reg_romask{RADIALRESETX2_REG_ID}  := X"00000000";\
 p_reg_romask{RADIALRESETXY_REG_ID}  := X"00000000";\
 p_reg_romask{RADIALRESETY2_REG_ID}  := X"00000000";\
 p_reg_romask{UNSHARPCFG_REG_ID}  := X"00000000";\
 p_reg_romask{UNSHARPCOEF0_REG_ID}  := X"00000000";\
 p_reg_romask{UNSHARPCOEF1_REG_ID}  := X"00000000";\
 p_reg_romask{VSS_LUT_X_REG_ID}  := X"00000000";\
 p_reg_romask{VSS_LUT_Y_REG_ID}  := X"00000000";\
\
FEATURE p_func_en                             : D1<BOOLEAN>;  \
 p_func_en{CFGUNIT_CU1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU3_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU5_0_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU5_1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU6_0_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU6_1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU6_2_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU6_3_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CU7_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_0_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_2_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_3_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_4_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUE_5_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_0_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_2_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_3_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_4_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_5_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUR_6_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUS_0_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUS_1_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUS_2_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUS_3_REG_ID}  := FALSE; \
 p_func_en{CFGUNIT_CUV_REG_ID}  := FALSE; \
 p_func_en{CUCFG0_REG_ID}  := FALSE; \
 p_func_en{CUCFG1_REG_ID}  := FALSE; \
 p_func_en{DFD_DATA_READ_CMD_REG_ID}  := FALSE; \
 p_func_en{DFD_DATA_READ_COMPLETION_REG_ID}  := TRUE; \
 p_func_en{DFD_EN_REG_ID}  := FALSE; \
 p_func_en{DFD_SINGLE_STEP_REG_ID}  := FALSE; \
 p_func_en{DFD_TRACED_DATA_REG_ID}  := TRUE; \
 p_func_en{DFD_TRACED_DATA_VALID_REG_ID}  := TRUE; \
 p_func_en{HW_ASSR_CLEAR_REG_ID}  := FALSE; \
 p_func_en{HW_ASSR_MASK_REG_ID}  := FALSE; \
 p_func_en{HW_ASSR_RAW_STAT_REG_ID}  := TRUE; \
 p_func_en{HW_ASSR_STAT_REG_ID}  := TRUE; \
 p_func_en{IEFD_CONFIG_REG_ID}  := FALSE; \
 p_func_en{IEFD_CONTROL_REG_ID}  := FALSE; \
 p_func_en{M_FAR_W_REG_ID}  := FALSE; \
 p_func_en{M_RAD_FAR_W_REG_ID}  := FALSE; \
 p_func_en{M_SHRPN_NEGA_LMT_DIR_REG_ID}  := FALSE; \
 p_func_en{M_SHRPN_NEGA_LMT_TXT_REG_ID}  := FALSE; \
 p_func_en{M_SHRPN_POSI_LMT_DIR_REG_ID}  := FALSE; \
 p_func_en{M_SHRPN_POSI_LMT_TXT_REG_ID}  := FALSE; \
 p_func_en{PWR_FEATURE_REG_ID}  := FALSE; \
 p_func_en{RADIALCFG_REG_ID}  := FALSE; \
 p_func_en{RADIALRESETX2_REG_ID}  := FALSE; \
 p_func_en{RADIALRESETXY_REG_ID}  := FALSE; \
 p_func_en{RADIALRESETY2_REG_ID}  := FALSE; \
 p_func_en{UNSHARPCFG_REG_ID}  := FALSE; \
 p_func_en{UNSHARPCOEF0_REG_ID}  := FALSE; \
 p_func_en{UNSHARPCOEF1_REG_ID}  := FALSE; \
 p_func_en{VSS_LUT_X_REG_ID}  := FALSE; \
 p_func_en{VSS_LUT_Y_REG_ID}  := FALSE; \


#define FF_IEFD_CCBCR_SIGNALS \
SIGNAL func_en                                : D1<BIT>(FF_IEFD_NOF_REGS_BANK); \
SIGNAL wire_reg_we                            : D1<BIT>(FF_IEFD_NOF_REGS_BANK); \
SIGNAL wire_reg_outputs                       : D1<BITVECTOR>(p_data_width); \
SIGNAL func_data                              : D1<BITVECTOR>(p_data_width);

#define CFGUNIT_CU1_A01_RANGE   26 DOWNTO 18
#define CFGUNIT_CU1_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CU1_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CU3_A01_RANGE   26 DOWNTO 18
#define CFGUNIT_CU3_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CU3_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CU5_0_A01_RANGE   26 DOWNTO 18
#define CFGUNIT_CU5_0_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CU5_0_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CU5_1_B01_RANGE   7 DOWNTO 0
#define CFGUNIT_CU6_0_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CU6_0_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CU6_0_X2_RANGE   26 DOWNTO 18
#define CFGUNIT_CU6_1_A01_RANGE   17 DOWNTO 9
#define CFGUNIT_CU6_1_A12_RANGE   26 DOWNTO 18
#define CFGUNIT_CU6_1_X3_RANGE   8 DOWNTO 0
#define CFGUNIT_CU6_2_A23_RANGE   8 DOWNTO 0
#define CFGUNIT_CU6_2_B01_RANGE   16 DOWNTO 9
#define CFGUNIT_CU6_2_B12_RANGE   24 DOWNTO 17
#define CFGUNIT_CU6_3_B23_RANGE   7 DOWNTO 0
#define CFGUNIT_CU7_A01_RANGE   26 DOWNTO 18
#define CFGUNIT_CU7_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CU7_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_0_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_0_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_0_X2_RANGE   26 DOWNTO 18
#define CFGUNIT_CUE_1_X3_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_1_X4_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_1_X5_RANGE   26 DOWNTO 18
#define CFGUNIT_CUE_2_A01_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_2_A12_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_2_A23_RANGE   26 DOWNTO 18
#define CFGUNIT_CUE_3_A34_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_3_A45_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_4_B01_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_4_B12_RANGE   17 DOWNTO 9
#define CFGUNIT_CUE_4_B23_RANGE   26 DOWNTO 18
#define CFGUNIT_CUE_5_B34_RANGE   8 DOWNTO 0
#define CFGUNIT_CUE_5_B45_RANGE   17 DOWNTO 9
#define CFGUNIT_CUR_0_X0_RANGE   7 DOWNTO 0
#define CFGUNIT_CUR_0_X1_RANGE   15 DOWNTO 8
#define CFGUNIT_CUR_0_X2_RANGE   23 DOWNTO 16
#define CFGUNIT_CUR_0_X3_RANGE   31 DOWNTO 24
#define CFGUNIT_CUR_1_X4_RANGE   7 DOWNTO 0
#define CFGUNIT_CUR_1_X5_RANGE   15 DOWNTO 8
#define CFGUNIT_CUR_2_A01_RANGE   15 DOWNTO 0
#define CFGUNIT_CUR_2_A12_RANGE   31 DOWNTO 16
#define CFGUNIT_CUR_3_A23_RANGE   15 DOWNTO 0
#define CFGUNIT_CUR_3_A34_RANGE   31 DOWNTO 16
#define CFGUNIT_CUR_4_A45_RANGE   15 DOWNTO 0
#define CFGUNIT_CUR_5_B01_RANGE   9 DOWNTO 0
#define CFGUNIT_CUR_5_B12_RANGE   19 DOWNTO 10
#define CFGUNIT_CUR_5_B23_RANGE   29 DOWNTO 20
#define CFGUNIT_CUR_6_B34_RANGE   9 DOWNTO 0
#define CFGUNIT_CUR_6_B45_RANGE   19 DOWNTO 10
#define CFGUNIT_CUS_0_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CUS_0_X1_RANGE   17 DOWNTO 9
#define CFGUNIT_CUS_0_X2_RANGE   26 DOWNTO 18
#define CFGUNIT_CUS_1_A01_RANGE   17 DOWNTO 9
#define CFGUNIT_CUS_1_A12_RANGE   26 DOWNTO 18
#define CFGUNIT_CUS_1_X3_RANGE   8 DOWNTO 0
#define CFGUNIT_CUS_2_A23_RANGE   8 DOWNTO 0
#define CFGUNIT_CUS_2_B01_RANGE   16 DOWNTO 9
#define CFGUNIT_CUS_2_B12_RANGE   24 DOWNTO 17
#define CFGUNIT_CUS_3_B23_RANGE   7 DOWNTO 0
#define CFGUNIT_CUV_A01_RANGE   26 DOWNTO 18
#define CFGUNIT_CUV_X0_RANGE   8 DOWNTO 0
#define CFGUNIT_CUV_X1_RANGE   17 DOWNTO 9
#define CUCFG0_M_CU6_POW_RANGE   6 DOWNTO 0
#define CUCFG0_M_CUUNSHARP_POW_RANGE   13 DOWNTO 8
#define CUCFG0_M_RAD_CU6_POW_RANGE   22 DOWNTO 16
#define CUCFG0_M_RAD_CUUNSHARP_POW_RANGE   29 DOWNTO 24
#define CUCFG1_M_RADCU6_X1_RANGE   8 DOWNTO 0
#define CUCFG1_M_RADCUUNSHARP_X1_RANGE   18 DOWNTO 10
#define DFD_DATA_READ_CMD_FETCH_RANGE   0
#define DFD_DATA_READ_COMPLETION_RD_COMP_RANGE   0
#define DFD_EN_DFD_EN_RANGE   0
#define DFD_EN_USE_PREV_TRACE_CHAIN_RANGE   8
#define DFD_EN_USE_PREV_TRIG_CHAIN_RANGE   4
#define DFD_SINGLE_STEP_SINGLE_STEP_RANGE   0
#define DFD_TRACED_DATA_DFD_TRACED_DATA_RANGE   31 DOWNTO 0
#define DFD_TRACED_DATA_VALID_DATA_VALID_RANGE   0
#define HW_ASSR_CLEAR_CLEAR_RANGE   3 DOWNTO 0
#define HW_ASSR_MASK_MASK_RANGE   3 DOWNTO 0
#define HW_ASSR_RAW_STAT_STAT_RANGE   3 DOWNTO 0
#define HW_ASSR_STAT_STAT_RANGE   3 DOWNTO 0
#define IEFD_CONFIG_M_CLAMP_STITCH_RANGE   13 DOWNTO 8
#define IEFD_CONFIG_M_DIRECT_METRIC_UPDATE_RANGE   20 DOWNTO 16
#define IEFD_CONFIG_M_ED_HORVER_DIAG_COEFF_RANGE   30 DOWNTO 24
#define IEFD_CONFIG_M_HORVER_DIAG_COEFF_RANGE   6 DOWNTO 0
#define IEFD_CONTROL_M_DENOISE_EN_RANGE   1
#define IEFD_CONTROL_M_DIRECT_SMOOTH_EN_RANGE   2
#define IEFD_CONTROL_M_IEFD_EN_RANGE   0
#define IEFD_CONTROL_M_RAD_ENABLE_RANGE   3
#define IEFD_CONTROL_M_VSSNLM_EN_RANGE   4
#define M_FAR_W_DIR_DNS_RANGE   14 DOWNTO 8
#define M_FAR_W_DIR_SHARP_RANGE   6 DOWNTO 0
#define M_FAR_W_M_NDIR_DNS_POWR_RANGE   22 DOWNTO 16
#define M_RAD_FAR_W_DIR_DNS_RANGE   14 DOWNTO 8
#define M_RAD_FAR_W_DIR_SHARP_RANGE   6 DOWNTO 0
#define M_RAD_FAR_W_M_RAD_NDIR_DNS_POWR_RANGE   22 DOWNTO 16
#define M_SHRPN_NEGA_LMT_DIR_VALUE_RANGE   12 DOWNTO 0
#define M_SHRPN_NEGA_LMT_TXT_VALUE_RANGE   12 DOWNTO 0
#define M_SHRPN_POSI_LMT_DIR_VALUE_RANGE   12 DOWNTO 0
#define M_SHRPN_POSI_LMT_TXT_VALUE_RANGE   12 DOWNTO 0
#define PWR_FEATURE_EMPTY_EN_RANGE   0
#define PWR_FEATURE_MOL_EN_RANGE   1
#define RADIALCFG_M_RAD_INV_R2_RANGE   14 DOWNTO 8
#define RADIALCFG_M_RAD_NF_RANGE   3 DOWNTO 0
#define RADIALRESETX2_X2_RANGE   23 DOWNTO 0
#define RADIALRESETXY_X_RANGE   12 DOWNTO 0
#define RADIALRESETXY_Y_RANGE   28 DOWNTO 16
#define RADIALRESETY2_Y2_RANGE   23 DOWNTO 0
#define UNSHARPCFG_M_UNSHARP_AMOUNT_RANGE   16 DOWNTO 8
#define UNSHARPCFG_M_UNSHARP_WEIGHT_RANGE   6 DOWNTO 0
#define UNSHARPCOEF0_C00_RANGE   8 DOWNTO 0
#define UNSHARPCOEF0_C01_RANGE   17 DOWNTO 9
#define UNSHARPCOEF0_C02_RANGE   26 DOWNTO 18
#define UNSHARPCOEF1_C11_RANGE   8 DOWNTO 0
#define UNSHARPCOEF1_C12_RANGE   17 DOWNTO 9
#define UNSHARPCOEF1_C22_RANGE   26 DOWNTO 18
#define VSS_LUT_X_M_VS_X0_RANGE   7 DOWNTO 0
#define VSS_LUT_X_M_VS_X1_RANGE   15 DOWNTO 8
#define VSS_LUT_X_M_VS_X2_RANGE   23 DOWNTO 16
#define VSS_LUT_Y_M_VS_Y1_RANGE   3 DOWNTO 0
#define VSS_LUT_Y_M_VS_Y2_RANGE   11 DOWNTO 8
#define VSS_LUT_Y_M_VS_Y3_RANGE   19 DOWNTO 16

#define CFGUNIT_CU1_A01_WIDTH  9
#define CFGUNIT_CU1_X0_WIDTH  9
#define CFGUNIT_CU1_X1_WIDTH  9
#define CFGUNIT_CU3_A01_WIDTH  9
#define CFGUNIT_CU3_X0_WIDTH  9
#define CFGUNIT_CU3_X1_WIDTH  9
#define CFGUNIT_CU5_0_A01_WIDTH  9
#define CFGUNIT_CU5_0_X0_WIDTH  9
#define CFGUNIT_CU5_0_X1_WIDTH  9
#define CFGUNIT_CU5_1_B01_WIDTH  8
#define CFGUNIT_CU6_0_X0_WIDTH  9
#define CFGUNIT_CU6_0_X1_WIDTH  9
#define CFGUNIT_CU6_0_X2_WIDTH  9
#define CFGUNIT_CU6_1_A01_WIDTH  9
#define CFGUNIT_CU6_1_A12_WIDTH  9
#define CFGUNIT_CU6_1_X3_WIDTH  9
#define CFGUNIT_CU6_2_A23_WIDTH  9
#define CFGUNIT_CU6_2_B01_WIDTH  8
#define CFGUNIT_CU6_2_B12_WIDTH  8
#define CFGUNIT_CU6_3_B23_WIDTH  8
#define CFGUNIT_CU7_A01_WIDTH  9
#define CFGUNIT_CU7_X0_WIDTH  9
#define CFGUNIT_CU7_X1_WIDTH  9
#define CFGUNIT_CUE_0_X0_WIDTH  9
#define CFGUNIT_CUE_0_X1_WIDTH  9
#define CFGUNIT_CUE_0_X2_WIDTH  9
#define CFGUNIT_CUE_1_X3_WIDTH  9
#define CFGUNIT_CUE_1_X4_WIDTH  9
#define CFGUNIT_CUE_1_X5_WIDTH  9
#define CFGUNIT_CUE_2_A01_WIDTH  9
#define CFGUNIT_CUE_2_A12_WIDTH  9
#define CFGUNIT_CUE_2_A23_WIDTH  9
#define CFGUNIT_CUE_3_A34_WIDTH  9
#define CFGUNIT_CUE_3_A45_WIDTH  9
#define CFGUNIT_CUE_4_B01_WIDTH  9
#define CFGUNIT_CUE_4_B12_WIDTH  9
#define CFGUNIT_CUE_4_B23_WIDTH  9
#define CFGUNIT_CUE_5_B34_WIDTH  9
#define CFGUNIT_CUE_5_B45_WIDTH  9
#define CFGUNIT_CUR_0_X0_WIDTH  8
#define CFGUNIT_CUR_0_X1_WIDTH  8
#define CFGUNIT_CUR_0_X2_WIDTH  8
#define CFGUNIT_CUR_0_X3_WIDTH  8
#define CFGUNIT_CUR_1_X4_WIDTH  8
#define CFGUNIT_CUR_1_X5_WIDTH  8
#define CFGUNIT_CUR_2_A01_WIDTH  16
#define CFGUNIT_CUR_2_A12_WIDTH  16
#define CFGUNIT_CUR_3_A23_WIDTH  16
#define CFGUNIT_CUR_3_A34_WIDTH  16
#define CFGUNIT_CUR_4_A45_WIDTH  16
#define CFGUNIT_CUR_5_B01_WIDTH  10
#define CFGUNIT_CUR_5_B12_WIDTH  10
#define CFGUNIT_CUR_5_B23_WIDTH  10
#define CFGUNIT_CUR_6_B34_WIDTH  10
#define CFGUNIT_CUR_6_B45_WIDTH  10
#define CFGUNIT_CUS_0_X0_WIDTH  9
#define CFGUNIT_CUS_0_X1_WIDTH  9
#define CFGUNIT_CUS_0_X2_WIDTH  9
#define CFGUNIT_CUS_1_A01_WIDTH  9
#define CFGUNIT_CUS_1_A12_WIDTH  9
#define CFGUNIT_CUS_1_X3_WIDTH  9
#define CFGUNIT_CUS_2_A23_WIDTH  9
#define CFGUNIT_CUS_2_B01_WIDTH  8
#define CFGUNIT_CUS_2_B12_WIDTH  8
#define CFGUNIT_CUS_3_B23_WIDTH  8
#define CFGUNIT_CUV_A01_WIDTH  9
#define CFGUNIT_CUV_X0_WIDTH  9
#define CFGUNIT_CUV_X1_WIDTH  9
#define CUCFG0_M_CU6_POW_WIDTH  7
#define CUCFG0_M_CUUNSHARP_POW_WIDTH  6
#define CUCFG0_M_RAD_CU6_POW_WIDTH  7
#define CUCFG0_M_RAD_CUUNSHARP_POW_WIDTH  6
#define CUCFG1_M_RADCU6_X1_WIDTH  9
#define CUCFG1_M_RADCUUNSHARP_X1_WIDTH  9
#define DFD_DATA_READ_CMD_FETCH_WIDTH  1
#define DFD_DATA_READ_COMPLETION_RD_COMP_WIDTH  1
#define DFD_EN_DFD_EN_WIDTH  1
#define DFD_EN_USE_PREV_TRACE_CHAIN_WIDTH  1
#define DFD_EN_USE_PREV_TRIG_CHAIN_WIDTH  1
#define DFD_SINGLE_STEP_SINGLE_STEP_WIDTH  1
#define DFD_TRACED_DATA_DFD_TRACED_DATA_WIDTH  32
#define DFD_TRACED_DATA_VALID_DATA_VALID_WIDTH  1
#define HW_ASSR_CLEAR_CLEAR_WIDTH  4
#define HW_ASSR_MASK_MASK_WIDTH  4
#define HW_ASSR_RAW_STAT_STAT_WIDTH  4
#define HW_ASSR_STAT_STAT_WIDTH  4
#define IEFD_CONFIG_M_CLAMP_STITCH_WIDTH  6
#define IEFD_CONFIG_M_DIRECT_METRIC_UPDATE_WIDTH  5
#define IEFD_CONFIG_M_ED_HORVER_DIAG_COEFF_WIDTH  7
#define IEFD_CONFIG_M_HORVER_DIAG_COEFF_WIDTH  7
#define IEFD_CONTROL_M_DENOISE_EN_WIDTH  1
#define IEFD_CONTROL_M_DIRECT_SMOOTH_EN_WIDTH  1
#define IEFD_CONTROL_M_IEFD_EN_WIDTH  1
#define IEFD_CONTROL_M_RAD_ENABLE_WIDTH  1
#define IEFD_CONTROL_M_VSSNLM_EN_WIDTH  1
#define M_FAR_W_DIR_DNS_WIDTH  7
#define M_FAR_W_DIR_SHARP_WIDTH  7
#define M_FAR_W_M_NDIR_DNS_POWR_WIDTH  7
#define M_RAD_FAR_W_DIR_DNS_WIDTH  7
#define M_RAD_FAR_W_DIR_SHARP_WIDTH  7
#define M_RAD_FAR_W_M_RAD_NDIR_DNS_POWR_WIDTH  7
#define M_SHRPN_NEGA_LMT_DIR_VALUE_WIDTH  13
#define M_SHRPN_NEGA_LMT_TXT_VALUE_WIDTH  13
#define M_SHRPN_POSI_LMT_DIR_VALUE_WIDTH  13
#define M_SHRPN_POSI_LMT_TXT_VALUE_WIDTH  13
#define PWR_FEATURE_EMPTY_EN_WIDTH  1
#define PWR_FEATURE_MOL_EN_WIDTH  1
#define RADIALCFG_M_RAD_INV_R2_WIDTH  7
#define RADIALCFG_M_RAD_NF_WIDTH  4
#define RADIALRESETX2_X2_WIDTH  24
#define RADIALRESETXY_X_WIDTH  13
#define RADIALRESETXY_Y_WIDTH  13
#define RADIALRESETY2_Y2_WIDTH  24
#define UNSHARPCFG_M_UNSHARP_AMOUNT_WIDTH  9
#define UNSHARPCFG_M_UNSHARP_WEIGHT_WIDTH  7
#define UNSHARPCOEF0_C00_WIDTH  9
#define UNSHARPCOEF0_C01_WIDTH  9
#define UNSHARPCOEF0_C02_WIDTH  9
#define UNSHARPCOEF1_C11_WIDTH  9
#define UNSHARPCOEF1_C12_WIDTH  9
#define UNSHARPCOEF1_C22_WIDTH  9
#define VSS_LUT_X_M_VS_X0_WIDTH  8
#define VSS_LUT_X_M_VS_X1_WIDTH  8
#define VSS_LUT_X_M_VS_X2_WIDTH  8
#define VSS_LUT_Y_M_VS_Y1_WIDTH  4
#define VSS_LUT_Y_M_VS_Y2_WIDTH  4
#define VSS_LUT_Y_M_VS_Y3_WIDTH  4


#endif
