
#define input_system_unis_logic_sp_control_tile_sp_type sp2600_control
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_stat_ip_cell_port_bus_slave_port                 input_system_unis_logic_sp_control_tile_sp_sl_stat_ip
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port(m)         sp2600_control_sl_stat_ip_cell_port
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_control_sl_stat_ip_, m), _address)
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_stat_ip_cell_port_connected_cell_port_message(m) NULL
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_dmem_ip_cell_port_bus_slave_port                 input_system_unis_logic_sp_control_tile_sp_sl_dmem_ip
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port(m)         sp2600_control_sl_dmem_ip_cell_port
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(sp2600_control_sl_dmem_ip_, m), _address)
#define input_system_unis_logic_sp_control_tile_spsp2600_control_sl_dmem_ip_cell_port_connected_cell_port_message(m) NULL
#define input_system_unis_logic_sp_control_tile_spsp2600_control_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define input_system_unis_logic_sp_control_tile_spsp2600_control_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define input_system_unis_logic_sp_control_tile_spsp2600_control_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define input_system_unis_logic_sp_control_tile_sp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port

#define input_system_unis_logic_sp_control_tile_sp_sl_stat_ip_error_message NULL
#define input_system_unis_logic_sp_control_tile_sp_sl_stat_ip_master_port_address 0x0
#define input_system_unis_logic_sp_control_tile_sp_sl_dmem_ip_error_message NULL
#define input_system_unis_logic_sp_control_tile_sp_sl_dmem_ip_master_port_address 0x8000
#define input_system_unis_logic_sp_control_tile_sp_imt_op_data_width 0x20
#define input_system_unis_logic_sp_control_tile_sp_qmt_op_data_width 0x20
#define input_system_unis_logic_sp_control_tile_sp_cmt_op_data_width 0x20
#define input_system_unis_logic_sp_control_tile_sp_xmt_op_data_width 0x20

