intel_fabric_logging-objs  := intel_fw_logging.o intel_fabricerr_status.o

obj-$(CONFIG_A1026)		+= a1026.o
obj-$(CONFIG_BCM_BT_LPM)        += bcm-lpm/
obj-$(CONFIG_INTEL_ST_LD)       += intel_ld/
obj-$(CONFIG_SCU_LOGGING)	+= intel_fabric_logging.o
obj-y                           += ti-st/
obj-$(CONFIG_UUID)		+= uuid.o
obj-$(CONFIG_EMMC_IPANIC)	+= emmc_ipanic.o
obj-$(CONFIG_SENSORS_APDS990X_FORK) += apds990x.o
obj-y                           += tp2l/
obj-$(CONFIG_INTEL_IQVANDROID)  += iqvandroid/
obj-$(CONFIG_RAWIO)             += rawio/
obj-$(CONFIG_KCT_DAEMON)	+= kct_daemon.o
obj-y				+= tp2e/
obj-$(CONFIG_FPS_THROTTLE)	+= fps_throttle.o
obj-$(CONFIG_KL03_HINGE)	+= kl03-hinge.o
