#
#  Copyright (c) 2014, ASUSTek, Inc. All Rights Reserved.
#  Written by chih-hsuan chang chih-hsuan_chang@asus.com
#

obj-$(CONFIG_PROC_FS) 			+= asus_battery_proc_fs.o
obj-$(CONFIG_ASUS_ENGINEER_MODE) 	+= asus_battery_proc_fs_asustag.o
obj-$(CONFIG_BATTERY_MM8033)		+= mm8033_battery.o
obj-$(CONFIG_SMB1357_CHARGER)		+= smb1357_charger.o
obj-$(CONFIG_A500CG_BATTERY_SMB347)	+= battery_smb347.o
obj-$(CONFIG_ASUS_BATTERY_POWER)        += asus_battery_power.o
obj-$(CONFIG_BATTERY_MAX17058)      	+= max17058_battery.o
